import typing
T = typing.TypeVar('T')

class VoidPtr:
    def __init__(self, *args, **kwargs) -> None: ...
    def toBytes(self, *args, **kwargs) -> typing.Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __int__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __len__(self) -> int: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

def _unpickle_enum(*args, **kwargs) -> typing.Any: ...
def createdByPython(*args, **kwargs) -> typing.Any: ...
def delete(*args, **kwargs) -> typing.Any: ...
def dump(*args, **kwargs) -> typing.Any: ...
def getAllValidWrappers(*args, **kwargs) -> typing.Any: ...
def getCppPointer(*args, **kwargs) -> typing.Any: ...
def invalidate(*args, **kwargs) -> typing.Any: ...
def isValid(*args, **kwargs) -> typing.Any: ...
def ownedByPython(*args, **kwargs) -> typing.Any: ...
def wrapInstance(*args, **kwargs) -> typing.Any: ...

class Object:
    pass
