from typing import Any, Callable, ClassVar, List, Union

from typing import overload
import PySide2.QtCore
import PySide2.QtGui
import shiboken2
import typing
T = typing.TypeVar('T')

class QMacPasteboardMime(shiboken2.Object):
    class QMacPasteboardMimeType:
        MIME_ALL: ClassVar[QMacPasteboardMime.QMacPasteboardMimeType] = ...
        MIME_CLIP: ClassVar[QMacPasteboardMime.QMacPasteboardMimeType] = ...
        MIME_DND: ClassVar[QMacPasteboardMime.QMacPasteboardMimeType] = ...
        MIME_QT3_CONVERTOR: ClassVar[QMacPasteboardMime.QMacPasteboardMimeType] = ...
        MIME_QT_CONVERTOR: ClassVar[QMacPasteboardMime.QMacPasteboardMimeType] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QMacPasteboardMime.QMacPasteboardMimeType: ...
        def __and__(self, other: typing.SupportsInt) -> QMacPasteboardMime.QMacPasteboardMimeType: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QMacPasteboardMime.QMacPasteboardMimeType: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QMacPasteboardMime.QMacPasteboardMimeType: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QMacPasteboardMime.QMacPasteboardMimeType: ...
        def __rand__(self, other: typing.SupportsInt) -> QMacPasteboardMime.QMacPasteboardMimeType: ...
        def __rmul__(self, other: typing.SupportsInt) -> QMacPasteboardMime.QMacPasteboardMimeType: ...
        def __ror__(self, other: typing.SupportsInt) -> QMacPasteboardMime.QMacPasteboardMimeType: ...
        def __rsub__(self, other: typing.SupportsInt) -> QMacPasteboardMime.QMacPasteboardMimeType: ...
        def __rxor__(self, other: typing.SupportsInt) -> QMacPasteboardMime.QMacPasteboardMimeType: ...
        def __sub__(self, other: typing.SupportsInt) -> QMacPasteboardMime.QMacPasteboardMimeType: ...
        def __xor__(self, other: typing.SupportsInt) -> QMacPasteboardMime.QMacPasteboardMimeType: ...
    MIME_ALL: ClassVar[QMacPasteboardMime.QMacPasteboardMimeType] = ...
    MIME_CLIP: ClassVar[QMacPasteboardMime.QMacPasteboardMimeType] = ...
    MIME_DND: ClassVar[QMacPasteboardMime.QMacPasteboardMimeType] = ...
    MIME_QT3_CONVERTOR: ClassVar[QMacPasteboardMime.QMacPasteboardMimeType] = ...
    MIME_QT_CONVERTOR: ClassVar[QMacPasteboardMime.QMacPasteboardMimeType] = ...
    def __init__(self, arg__1: int) -> None: ...
    def canConvert(self, mime: str, flav: str) -> bool: ...
    def convertFromMime(self, mime: str, data: typing.Any, flav: str) -> typing.List[PySide2.QtCore.QByteArray]: ...
    def convertToMime(self, mime: str, data: typing.Sequence[PySide2.QtCore.QByteArray], flav: str) -> typing.Any: ...
    def convertorName(self) -> str: ...
    def count(self, mimeData: PySide2.QtCore.QMimeData) -> int: ...
    def flavorFor(self, mime: str) -> str: ...
    def mimeFor(self, flav: str) -> str: ...

class QMacToolBar(PySide2.QtCore.QObject):
    staticMetaObject: ClassVar[PySide2.QtCore.QMetaObject] = ...
    @overload
    def __init__(self, identifier: str, parent: typing.Union[PySide2.QtCore.QObject,None] = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    @overload
    def __init__(self, parent: typing.Union[PySide2.QtCore.QObject,None] = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def addAllowedItem(self, icon: PySide2.QtGui.QIcon, text: str) -> QMacToolBarItem: ...
    def addAllowedStandardItem(self, standardItem: QMacToolBarItem.StandardItem) -> QMacToolBarItem: ...
    def addItem(self, icon: PySide2.QtGui.QIcon, text: str) -> QMacToolBarItem: ...
    def addSeparator(self) -> None: ...
    def addStandardItem(self, standardItem: QMacToolBarItem.StandardItem) -> QMacToolBarItem: ...
    def allowedItems(self) -> typing.List[QMacToolBarItem]: ...
    def attachToWindow(self, window: PySide2.QtGui.QWindow) -> None: ...
    def detachFromWindow(self) -> None: ...
    def items(self) -> typing.List[QMacToolBarItem]: ...
    def setAllowedItems(self, allowedItems: typing.Sequence[QMacToolBarItem]) -> None: ...
    def setItems(self, items: typing.Sequence[QMacToolBarItem]) -> None: ...

class QMacToolBarItem(PySide2.QtCore.QObject):
    class StandardItem:
        FlexibleSpace: ClassVar[QMacToolBarItem.StandardItem] = ...
        NoStandardItem: ClassVar[QMacToolBarItem.StandardItem] = ...
        Space: ClassVar[QMacToolBarItem.StandardItem] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QMacToolBarItem.StandardItem: ...
        def __and__(self, other: typing.SupportsInt) -> QMacToolBarItem.StandardItem: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QMacToolBarItem.StandardItem: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QMacToolBarItem.StandardItem: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QMacToolBarItem.StandardItem: ...
        def __rand__(self, other: typing.SupportsInt) -> QMacToolBarItem.StandardItem: ...
        def __rmul__(self, other: typing.SupportsInt) -> QMacToolBarItem.StandardItem: ...
        def __ror__(self, other: typing.SupportsInt) -> QMacToolBarItem.StandardItem: ...
        def __rsub__(self, other: typing.SupportsInt) -> QMacToolBarItem.StandardItem: ...
        def __rxor__(self, other: typing.SupportsInt) -> QMacToolBarItem.StandardItem: ...
        def __sub__(self, other: typing.SupportsInt) -> QMacToolBarItem.StandardItem: ...
        def __xor__(self, other: typing.SupportsInt) -> QMacToolBarItem.StandardItem: ...
    FlexibleSpace: ClassVar[QMacToolBarItem.StandardItem] = ...
    NoStandardItem: ClassVar[QMacToolBarItem.StandardItem] = ...
    Space: ClassVar[QMacToolBarItem.StandardItem] = ...
    activated: ClassVar[PySide2.QtCore.Signal] = ...
    staticMetaObject: ClassVar[PySide2.QtCore.QMetaObject] = ...
    def __init__(self, parent: typing.Union[PySide2.QtCore.QObject,None] = ..., activated: typing.Callable = ..., destroyed: typing.Callable = ..., icon: PySide2.QtGui.QIcon = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., selectable: bool = ..., standardItem: QMacToolBarItem.StandardItem = ..., text: str = ...) -> None: ...
    def icon(self) -> PySide2.QtGui.QIcon: ...
    def selectable(self) -> bool: ...
    def setIcon(self, icon: PySide2.QtGui.QIcon) -> None: ...
    def setSelectable(self, selectable: bool) -> None: ...
    def setStandardItem(self, standardItem: QMacToolBarItem.StandardItem) -> None: ...
    def setText(self, text: str) -> None: ...
    def standardItem(self) -> QMacToolBarItem.StandardItem: ...
    def text(self) -> str: ...

def qRegisterDraggedTypes(types: typing.Sequence[str]) -> None: ...
