from typing import Any, Callable, ClassVar, Dict, List, Optional, Tuple, Union

from typing import overload
import PySide2.QtCore
import shiboken2
import typing
T = typing.TypeVar('T')

class QGeoAddress(shiboken2.Object):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, other: QGeoAddress) -> None: ...
    def city(self) -> str: ...
    def clear(self) -> None: ...
    def country(self) -> str: ...
    def countryCode(self) -> str: ...
    def county(self) -> str: ...
    def district(self) -> str: ...
    def isEmpty(self) -> bool: ...
    def isTextGenerated(self) -> bool: ...
    def postalCode(self) -> str: ...
    def setCity(self, city: str) -> None: ...
    def setCountry(self, country: str) -> None: ...
    def setCountryCode(self, countryCode: str) -> None: ...
    def setCounty(self, county: str) -> None: ...
    def setDistrict(self, district: str) -> None: ...
    def setPostalCode(self, postalCode: str) -> None: ...
    def setState(self, state: str) -> None: ...
    def setStreet(self, street: str) -> None: ...
    def setText(self, text: str) -> None: ...
    def state(self) -> str: ...
    def street(self) -> str: ...
    def text(self) -> str: ...
    def __copy__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QGeoAreaMonitorInfo(shiboken2.Object):
    @overload
    def __init__(self, name: str = ...) -> None: ...
    @overload
    def __init__(self, other: QGeoAreaMonitorInfo) -> None: ...
    def area(self) -> QGeoShape: ...
    def expiration(self) -> PySide2.QtCore.QDateTime: ...
    def identifier(self) -> str: ...
    def isPersistent(self) -> bool: ...
    def isValid(self) -> bool: ...
    def name(self) -> str: ...
    def notificationParameters(self) -> typing.Dict[str,typing.Any]: ...
    def setArea(self, newShape: QGeoShape) -> None: ...
    def setExpiration(self, expiry: PySide2.QtCore.QDateTime) -> None: ...
    def setName(self, name: str) -> None: ...
    def setNotificationParameters(self, parameters: typing.Dict[str,typing.Any]) -> None: ...
    def setPersistent(self, isPersistent: bool) -> None: ...
    def __copy__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lshift__(self, arg__1: PySide2.QtCore.QDataStream) -> PySide2.QtCore.QDataStream: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __rlshift__(self, other) -> Any: ...
    def __rrshift__(self, other) -> Any: ...
    def __rshift__(self, arg__1: PySide2.QtCore.QDataStream) -> PySide2.QtCore.QDataStream: ...

class QGeoAreaMonitorSource(PySide2.QtCore.QObject):
    class AreaMonitorFeature:
        AnyAreaMonitorFeature: ClassVar[QGeoAreaMonitorSource.AreaMonitorFeature] = ...
        PersistentAreaMonitorFeature: ClassVar[QGeoAreaMonitorSource.AreaMonitorFeature] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __and__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.AreaMonitorFeatures: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __invert__(self) -> QGeoAreaMonitorSource.AreaMonitorFeature: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.AreaMonitorFeatures: ...
        def __rand__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.AreaMonitorFeatures: ...
        def __ror__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.AreaMonitorFeatures: ...
        def __rxor__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.AreaMonitorFeatures: ...
        def __xor__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.AreaMonitorFeatures: ...

    class AreaMonitorFeatures:
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __and__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.AreaMonitorFeatures: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __invert__(self) -> QGeoAreaMonitorSource.AreaMonitorFeatures: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.AreaMonitorFeatures: ...
        def __rand__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.AreaMonitorFeatures: ...
        def __ror__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.AreaMonitorFeatures: ...
        def __rxor__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.AreaMonitorFeatures: ...
        def __xor__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.AreaMonitorFeatures: ...

    class Error:
        AccessError: ClassVar[QGeoAreaMonitorSource.Error] = ...
        InsufficientPositionInfo: ClassVar[QGeoAreaMonitorSource.Error] = ...
        NoError: ClassVar[QGeoAreaMonitorSource.Error] = ...
        UnknownSourceError: ClassVar[QGeoAreaMonitorSource.Error] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.Error: ...
        def __and__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.Error: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.Error: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.Error: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.Error: ...
        def __rand__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.Error: ...
        def __rmul__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.Error: ...
        def __ror__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.Error: ...
        def __rsub__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.Error: ...
        def __rxor__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.Error: ...
        def __sub__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.Error: ...
        def __xor__(self, other: typing.SupportsInt) -> QGeoAreaMonitorSource.Error: ...
    AccessError: ClassVar[QGeoAreaMonitorSource.Error] = ...
    AnyAreaMonitorFeature: ClassVar[QGeoAreaMonitorSource.AreaMonitorFeature] = ...
    InsufficientPositionInfo: ClassVar[QGeoAreaMonitorSource.Error] = ...
    NoError: ClassVar[QGeoAreaMonitorSource.Error] = ...
    PersistentAreaMonitorFeature: ClassVar[QGeoAreaMonitorSource.AreaMonitorFeature] = ...
    UnknownSourceError: ClassVar[QGeoAreaMonitorSource.Error] = ...
    areaEntered: ClassVar[PySide2.QtCore.Signal] = ...
    areaExited: ClassVar[PySide2.QtCore.Signal] = ...
    error: ClassVar[PySide2.QtCore.Signal] = ...
    monitorExpired: ClassVar[PySide2.QtCore.Signal] = ...
    staticMetaObject: ClassVar[PySide2.QtCore.QMetaObject] = ...
    def __init__(self, parent: typing.Optional[PySide2.QtCore.QObject], destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    @overload
    def activeMonitors(self) -> typing.List[QGeoAreaMonitorInfo]: ...
    @overload
    def activeMonitors(self, lookupArea: QGeoShape) -> typing.List[QGeoAreaMonitorInfo]: ...
    @classmethod
    def availableSources(cls) -> typing.List[str]: ...
    @classmethod
    def createDefaultSource(cls, parent: typing.Optional[PySide2.QtCore.QObject]) -> QGeoAreaMonitorSource: ...
    @classmethod
    def createSource(cls, sourceName: str, parent: typing.Optional[PySide2.QtCore.QObject]) -> QGeoAreaMonitorSource: ...
    def positionInfoSource(self) -> QGeoPositionInfoSource: ...
    def requestUpdate(self, monitor: QGeoAreaMonitorInfo, signal: bytes) -> bool: ...
    def setPositionInfoSource(self, source: QGeoPositionInfoSource) -> None: ...
    def sourceName(self) -> str: ...
    def startMonitoring(self, monitor: QGeoAreaMonitorInfo) -> bool: ...
    def stopMonitoring(self, monitor: QGeoAreaMonitorInfo) -> bool: ...
    def supportedAreaMonitorFeatures(self) -> typing.Union[QGeoAreaMonitorSource.AreaMonitorFeatures,QGeoAreaMonitorSource.AreaMonitorFeature]: ...

class QGeoCircle(QGeoShape):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, center: QGeoCoordinate, radius: float = ...) -> None: ...
    @overload
    def __init__(self, other: QGeoCircle) -> None: ...
    @overload
    def __init__(self, other: QGeoShape) -> None: ...
    def center(self) -> QGeoCoordinate: ...
    def extendCircle(self, coordinate: QGeoCoordinate) -> None: ...
    def radius(self) -> float: ...
    def setCenter(self, center: QGeoCoordinate) -> None: ...
    def setRadius(self, radius: float) -> None: ...
    def toString(self) -> str: ...
    def translate(self, degreesLatitude: float, degreesLongitude: float) -> None: ...
    def translated(self, degreesLatitude: float, degreesLongitude: float) -> QGeoCircle: ...
    def __copy__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QGeoCoordinate(shiboken2.Object):
    class CoordinateFormat:
        Degrees: ClassVar[QGeoCoordinate.CoordinateFormat] = ...
        DegreesMinutes: ClassVar[QGeoCoordinate.CoordinateFormat] = ...
        DegreesMinutesSeconds: ClassVar[QGeoCoordinate.CoordinateFormat] = ...
        DegreesMinutesSecondsWithHemisphere: ClassVar[QGeoCoordinate.CoordinateFormat] = ...
        DegreesMinutesWithHemisphere: ClassVar[QGeoCoordinate.CoordinateFormat] = ...
        DegreesWithHemisphere: ClassVar[QGeoCoordinate.CoordinateFormat] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateFormat: ...
        def __and__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateFormat: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateFormat: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateFormat: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateFormat: ...
        def __rand__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateFormat: ...
        def __rmul__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateFormat: ...
        def __ror__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateFormat: ...
        def __rsub__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateFormat: ...
        def __rxor__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateFormat: ...
        def __sub__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateFormat: ...
        def __xor__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateFormat: ...

    class CoordinateType:
        Coordinate2D: ClassVar[QGeoCoordinate.CoordinateType] = ...
        Coordinate3D: ClassVar[QGeoCoordinate.CoordinateType] = ...
        InvalidCoordinate: ClassVar[QGeoCoordinate.CoordinateType] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateType: ...
        def __and__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateType: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateType: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateType: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateType: ...
        def __rand__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateType: ...
        def __rmul__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateType: ...
        def __ror__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateType: ...
        def __rsub__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateType: ...
        def __rxor__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateType: ...
        def __sub__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateType: ...
        def __xor__(self, other: typing.SupportsInt) -> QGeoCoordinate.CoordinateType: ...
    Coordinate2D: ClassVar[QGeoCoordinate.CoordinateType] = ...
    Coordinate3D: ClassVar[QGeoCoordinate.CoordinateType] = ...
    Degrees: ClassVar[QGeoCoordinate.CoordinateFormat] = ...
    DegreesMinutes: ClassVar[QGeoCoordinate.CoordinateFormat] = ...
    DegreesMinutesSeconds: ClassVar[QGeoCoordinate.CoordinateFormat] = ...
    DegreesMinutesSecondsWithHemisphere: ClassVar[QGeoCoordinate.CoordinateFormat] = ...
    DegreesMinutesWithHemisphere: ClassVar[QGeoCoordinate.CoordinateFormat] = ...
    DegreesWithHemisphere: ClassVar[QGeoCoordinate.CoordinateFormat] = ...
    InvalidCoordinate: ClassVar[QGeoCoordinate.CoordinateType] = ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, latitude: float, longitude: float) -> None: ...
    @overload
    def __init__(self, latitude: float, longitude: float, altitude: float) -> None: ...
    @overload
    def __init__(self, other: QGeoCoordinate) -> None: ...
    def altitude(self) -> float: ...
    def atDistanceAndAzimuth(self, distance: float, azimuth: float, distanceUp: float = ...) -> QGeoCoordinate: ...
    def azimuthTo(self, other: QGeoCoordinate) -> float: ...
    def distanceTo(self, other: QGeoCoordinate) -> float: ...
    def isValid(self) -> bool: ...
    def latitude(self) -> float: ...
    def longitude(self) -> float: ...
    def setAltitude(self, altitude: float) -> None: ...
    def setLatitude(self, latitude: float) -> None: ...
    def setLongitude(self, longitude: float) -> None: ...
    def toString(self, format: QGeoCoordinate.CoordinateFormat = ...) -> str: ...
    def type(self) -> QGeoCoordinate.CoordinateType: ...
    def __copy__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lshift__(self, stream: PySide2.QtCore.QDataStream) -> PySide2.QtCore.QDataStream: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __rlshift__(self, other) -> Any: ...
    def __rrshift__(self, other) -> Any: ...
    def __rshift__(self, stream: PySide2.QtCore.QDataStream) -> PySide2.QtCore.QDataStream: ...

class QGeoLocation(shiboken2.Object):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, other: QGeoLocation) -> None: ...
    def address(self) -> QGeoAddress: ...
    def boundingBox(self) -> QGeoRectangle: ...
    def coordinate(self) -> QGeoCoordinate: ...
    def extendedAttributes(self) -> typing.Dict[str,typing.Any]: ...
    def isEmpty(self) -> bool: ...
    def setAddress(self, address: QGeoAddress) -> None: ...
    def setBoundingBox(self, box: QGeoRectangle) -> None: ...
    def setCoordinate(self, position: QGeoCoordinate) -> None: ...
    def setExtendedAttributes(self, data: typing.Dict[str,typing.Any]) -> None: ...
    def __copy__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QGeoPath(QGeoShape):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, other: QGeoPath) -> None: ...
    @overload
    def __init__(self, other: QGeoShape) -> None: ...
    @overload
    def __init__(self, path: typing.Sequence[QGeoCoordinate], width: float = ...) -> None: ...
    def addCoordinate(self, coordinate: QGeoCoordinate) -> None: ...
    def clearPath(self) -> None: ...
    def containsCoordinate(self, coordinate: QGeoCoordinate) -> bool: ...
    def coordinateAt(self, index: int) -> QGeoCoordinate: ...
    def insertCoordinate(self, index: int, coordinate: QGeoCoordinate) -> None: ...
    def length(self, indexFrom: int = ..., indexTo: int = ...) -> float: ...
    def path(self) -> typing.List[QGeoCoordinate]: ...
    @overload
    def removeCoordinate(self, coordinate: QGeoCoordinate) -> None: ...
    @overload
    def removeCoordinate(self, index: int) -> None: ...
    def replaceCoordinate(self, index: int, coordinate: QGeoCoordinate) -> None: ...
    def setPath(self, path: typing.Sequence[QGeoCoordinate]) -> None: ...
    def setVariantPath(self, path: typing.Sequence[typing.Any]) -> None: ...
    def setWidth(self, width: float) -> None: ...
    def size(self) -> int: ...
    def toString(self) -> str: ...
    def translate(self, degreesLatitude: float, degreesLongitude: float) -> None: ...
    def translated(self, degreesLatitude: float, degreesLongitude: float) -> QGeoPath: ...
    def variantPath(self) -> typing.List[typing.Any]: ...
    def width(self) -> float: ...
    def __copy__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QGeoPolygon(QGeoShape):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, other: QGeoPolygon) -> None: ...
    @overload
    def __init__(self, other: QGeoShape) -> None: ...
    @overload
    def __init__(self, path: typing.Sequence[QGeoCoordinate]) -> None: ...
    def addCoordinate(self, coordinate: QGeoCoordinate) -> None: ...
    @overload
    def addHole(self, holePath: typing.Sequence[QGeoCoordinate]) -> None: ...
    @overload
    def addHole(self, holePath: typing.Any) -> None: ...
    def containsCoordinate(self, coordinate: QGeoCoordinate) -> bool: ...
    def coordinateAt(self, index: int) -> QGeoCoordinate: ...
    def hole(self, index: int) -> typing.List[typing.Any]: ...
    def holePath(self, index: int) -> typing.List[QGeoCoordinate]: ...
    def holesCount(self) -> int: ...
    def insertCoordinate(self, index: int, coordinate: QGeoCoordinate) -> None: ...
    def length(self, indexFrom: int = ..., indexTo: int = ...) -> float: ...
    def path(self) -> typing.List[QGeoCoordinate]: ...
    def perimeter(self) -> typing.List[typing.Any]: ...
    @overload
    def removeCoordinate(self, coordinate: QGeoCoordinate) -> None: ...
    @overload
    def removeCoordinate(self, index: int) -> None: ...
    def removeHole(self, index: int) -> None: ...
    def replaceCoordinate(self, index: int, coordinate: QGeoCoordinate) -> None: ...
    def setPath(self, path: typing.Sequence[QGeoCoordinate]) -> None: ...
    def setPerimeter(self, path: typing.Sequence[typing.Any]) -> None: ...
    def size(self) -> int: ...
    def toString(self) -> str: ...
    def translate(self, degreesLatitude: float, degreesLongitude: float) -> None: ...
    def translated(self, degreesLatitude: float, degreesLongitude: float) -> QGeoPolygon: ...
    def __copy__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QGeoPositionInfo(shiboken2.Object):
    class Attribute:
        Direction: ClassVar[QGeoPositionInfo.Attribute] = ...
        GroundSpeed: ClassVar[QGeoPositionInfo.Attribute] = ...
        HorizontalAccuracy: ClassVar[QGeoPositionInfo.Attribute] = ...
        MagneticVariation: ClassVar[QGeoPositionInfo.Attribute] = ...
        VerticalAccuracy: ClassVar[QGeoPositionInfo.Attribute] = ...
        VerticalSpeed: ClassVar[QGeoPositionInfo.Attribute] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QGeoPositionInfo.Attribute: ...
        def __and__(self, other: typing.SupportsInt) -> QGeoPositionInfo.Attribute: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QGeoPositionInfo.Attribute: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QGeoPositionInfo.Attribute: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QGeoPositionInfo.Attribute: ...
        def __rand__(self, other: typing.SupportsInt) -> QGeoPositionInfo.Attribute: ...
        def __rmul__(self, other: typing.SupportsInt) -> QGeoPositionInfo.Attribute: ...
        def __ror__(self, other: typing.SupportsInt) -> QGeoPositionInfo.Attribute: ...
        def __rsub__(self, other: typing.SupportsInt) -> QGeoPositionInfo.Attribute: ...
        def __rxor__(self, other: typing.SupportsInt) -> QGeoPositionInfo.Attribute: ...
        def __sub__(self, other: typing.SupportsInt) -> QGeoPositionInfo.Attribute: ...
        def __xor__(self, other: typing.SupportsInt) -> QGeoPositionInfo.Attribute: ...
    Direction: ClassVar[QGeoPositionInfo.Attribute] = ...
    GroundSpeed: ClassVar[QGeoPositionInfo.Attribute] = ...
    HorizontalAccuracy: ClassVar[QGeoPositionInfo.Attribute] = ...
    MagneticVariation: ClassVar[QGeoPositionInfo.Attribute] = ...
    VerticalAccuracy: ClassVar[QGeoPositionInfo.Attribute] = ...
    VerticalSpeed: ClassVar[QGeoPositionInfo.Attribute] = ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, coordinate: QGeoCoordinate, updateTime: PySide2.QtCore.QDateTime) -> None: ...
    @overload
    def __init__(self, other: QGeoPositionInfo) -> None: ...
    def attribute(self, attribute: QGeoPositionInfo.Attribute) -> float: ...
    def coordinate(self) -> QGeoCoordinate: ...
    def hasAttribute(self, attribute: QGeoPositionInfo.Attribute) -> bool: ...
    def isValid(self) -> bool: ...
    def removeAttribute(self, attribute: QGeoPositionInfo.Attribute) -> None: ...
    def setAttribute(self, attribute: QGeoPositionInfo.Attribute, value: float) -> None: ...
    def setCoordinate(self, coordinate: QGeoCoordinate) -> None: ...
    def setTimestamp(self, timestamp: PySide2.QtCore.QDateTime) -> None: ...
    def timestamp(self) -> PySide2.QtCore.QDateTime: ...
    def __copy__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lshift__(self, stream: PySide2.QtCore.QDataStream) -> PySide2.QtCore.QDataStream: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __rlshift__(self, other) -> Any: ...
    def __rrshift__(self, other) -> Any: ...
    def __rshift__(self, stream: PySide2.QtCore.QDataStream) -> PySide2.QtCore.QDataStream: ...

class QGeoPositionInfoSource(PySide2.QtCore.QObject):
    class Error:
        AccessError: ClassVar[QGeoPositionInfoSource.Error] = ...
        ClosedError: ClassVar[QGeoPositionInfoSource.Error] = ...
        NoError: ClassVar[QGeoPositionInfoSource.Error] = ...
        UnknownSourceError: ClassVar[QGeoPositionInfoSource.Error] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.Error: ...
        def __and__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.Error: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.Error: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.Error: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.Error: ...
        def __rand__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.Error: ...
        def __rmul__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.Error: ...
        def __ror__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.Error: ...
        def __rsub__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.Error: ...
        def __rxor__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.Error: ...
        def __sub__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.Error: ...
        def __xor__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.Error: ...

    class PositioningMethod:
        AllPositioningMethods: ClassVar[QGeoPositionInfoSource.PositioningMethod] = ...
        NoPositioningMethods: ClassVar[QGeoPositionInfoSource.PositioningMethod] = ...
        NonSatellitePositioningMethods: ClassVar[QGeoPositionInfoSource.PositioningMethod] = ...
        SatellitePositioningMethods: ClassVar[QGeoPositionInfoSource.PositioningMethod] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __and__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.PositioningMethods: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __invert__(self) -> QGeoPositionInfoSource.PositioningMethod: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.PositioningMethods: ...
        def __rand__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.PositioningMethods: ...
        def __ror__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.PositioningMethods: ...
        def __rxor__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.PositioningMethods: ...
        def __xor__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.PositioningMethods: ...

    class PositioningMethods:
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __and__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.PositioningMethods: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __invert__(self) -> QGeoPositionInfoSource.PositioningMethods: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.PositioningMethods: ...
        def __rand__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.PositioningMethods: ...
        def __ror__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.PositioningMethods: ...
        def __rxor__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.PositioningMethods: ...
        def __xor__(self, other: typing.SupportsInt) -> QGeoPositionInfoSource.PositioningMethods: ...
    AccessError: ClassVar[QGeoPositionInfoSource.Error] = ...
    AllPositioningMethods: ClassVar[QGeoPositionInfoSource.PositioningMethod] = ...
    ClosedError: ClassVar[QGeoPositionInfoSource.Error] = ...
    NoError: ClassVar[QGeoPositionInfoSource.Error] = ...
    NoPositioningMethods: ClassVar[QGeoPositionInfoSource.PositioningMethod] = ...
    NonSatellitePositioningMethods: ClassVar[QGeoPositionInfoSource.PositioningMethod] = ...
    SatellitePositioningMethods: ClassVar[QGeoPositionInfoSource.PositioningMethod] = ...
    UnknownSourceError: ClassVar[QGeoPositionInfoSource.Error] = ...
    error: ClassVar[PySide2.QtCore.Signal] = ...
    positionUpdated: ClassVar[PySide2.QtCore.Signal] = ...
    staticMetaObject: ClassVar[PySide2.QtCore.QMetaObject] = ...
    supportedPositioningMethodsChanged: ClassVar[PySide2.QtCore.Signal] = ...
    updateTimeout: ClassVar[PySide2.QtCore.Signal] = ...
    def __init__(self, parent: typing.Optional[PySide2.QtCore.QObject], destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    @classmethod
    def availableSources(cls) -> typing.List[str]: ...
    def backendProperty(self, name: str) -> typing.Any: ...
    @classmethod
    @overload
    def createDefaultSource(cls, parameters: typing.Dict[str,typing.Any], parent: typing.Optional[PySide2.QtCore.QObject]) -> QGeoPositionInfoSource: ...
    @classmethod
    @overload
    def createDefaultSource(cls, parent: typing.Optional[PySide2.QtCore.QObject]) -> QGeoPositionInfoSource: ...
    @classmethod
    @overload
    def createSource(cls, sourceName: str, parameters: typing.Dict[str,typing.Any], parent: typing.Optional[PySide2.QtCore.QObject]) -> QGeoPositionInfoSource: ...
    @classmethod
    @overload
    def createSource(cls, sourceName: str, parent: typing.Optional[PySide2.QtCore.QObject]) -> QGeoPositionInfoSource: ...
    def lastKnownPosition(self, fromSatellitePositioningMethodsOnly: bool = ...) -> QGeoPositionInfo: ...
    def minimumUpdateInterval(self) -> int: ...
    def preferredPositioningMethods(self) -> typing.Union[QGeoPositionInfoSource.PositioningMethods,QGeoPositionInfoSource.PositioningMethod]: ...
    def requestUpdate(self, timeout: int = ...) -> None: ...
    def setBackendProperty(self, name: str, value: typing.Any) -> bool: ...
    def setPreferredPositioningMethods(self, methods: typing.Union[QGeoPositionInfoSource.PositioningMethods,QGeoPositionInfoSource.PositioningMethod]) -> None: ...
    def setUpdateInterval(self, msec: int) -> None: ...
    def sourceName(self) -> str: ...
    def startUpdates(self) -> None: ...
    def stopUpdates(self) -> None: ...
    def supportedPositioningMethods(self) -> typing.Union[QGeoPositionInfoSource.PositioningMethods,QGeoPositionInfoSource.PositioningMethod]: ...
    def updateInterval(self) -> int: ...

class QGeoPositionInfoSourceFactory(shiboken2.Object):
    def __init__(self) -> None: ...
    def areaMonitor(self, parent: typing.Optional[PySide2.QtCore.QObject]) -> QGeoAreaMonitorSource: ...
    def positionInfoSource(self, parent: typing.Optional[PySide2.QtCore.QObject]) -> QGeoPositionInfoSource: ...
    def satelliteInfoSource(self, parent: typing.Optional[PySide2.QtCore.QObject]) -> QGeoSatelliteInfoSource: ...

class QGeoRectangle(QGeoShape):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, center: QGeoCoordinate, degreesWidth: float, degreesHeight: float) -> None: ...
    @overload
    def __init__(self, coordinates: typing.Sequence[QGeoCoordinate]) -> None: ...
    @overload
    def __init__(self, other: QGeoRectangle) -> None: ...
    @overload
    def __init__(self, other: QGeoShape) -> None: ...
    @overload
    def __init__(self, topLeft: QGeoCoordinate, bottomRight: QGeoCoordinate) -> None: ...
    def bottomLeft(self) -> QGeoCoordinate: ...
    def bottomRight(self) -> QGeoCoordinate: ...
    def center(self) -> QGeoCoordinate: ...
    @overload
    def contains(self, coordinate: QGeoCoordinate) -> bool: ...
    @overload
    def contains(self, rectangle: QGeoRectangle) -> bool: ...
    def extendRectangle(self, coordinate: QGeoCoordinate) -> None: ...
    def height(self) -> float: ...
    def intersects(self, rectangle: QGeoRectangle) -> bool: ...
    def setBottomLeft(self, bottomLeft: QGeoCoordinate) -> None: ...
    def setBottomRight(self, bottomRight: QGeoCoordinate) -> None: ...
    def setCenter(self, center: QGeoCoordinate) -> None: ...
    def setHeight(self, degreesHeight: float) -> None: ...
    def setTopLeft(self, topLeft: QGeoCoordinate) -> None: ...
    def setTopRight(self, topRight: QGeoCoordinate) -> None: ...
    def setWidth(self, degreesWidth: float) -> None: ...
    def toString(self) -> str: ...
    def topLeft(self) -> QGeoCoordinate: ...
    def topRight(self) -> QGeoCoordinate: ...
    def translate(self, degreesLatitude: float, degreesLongitude: float) -> None: ...
    def translated(self, degreesLatitude: float, degreesLongitude: float) -> QGeoRectangle: ...
    def united(self, rectangle: QGeoRectangle) -> QGeoRectangle: ...
    def width(self) -> float: ...
    def __copy__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ior__(self, rectangle: QGeoRectangle) -> QGeoRectangle: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __or__(self, rectangle: QGeoRectangle) -> QGeoRectangle: ...
    def __ror__(self, other) -> Any: ...

class QGeoSatelliteInfo(shiboken2.Object):
    class Attribute:
        Azimuth: ClassVar[QGeoSatelliteInfo.Attribute] = ...
        Elevation: ClassVar[QGeoSatelliteInfo.Attribute] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.Attribute: ...
        def __and__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.Attribute: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.Attribute: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.Attribute: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.Attribute: ...
        def __rand__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.Attribute: ...
        def __rmul__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.Attribute: ...
        def __ror__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.Attribute: ...
        def __rsub__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.Attribute: ...
        def __rxor__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.Attribute: ...
        def __sub__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.Attribute: ...
        def __xor__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.Attribute: ...

    class SatelliteSystem:
        GLONASS: ClassVar[QGeoSatelliteInfo.SatelliteSystem] = ...
        GPS: ClassVar[QGeoSatelliteInfo.SatelliteSystem] = ...
        Undefined: ClassVar[QGeoSatelliteInfo.SatelliteSystem] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.SatelliteSystem: ...
        def __and__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.SatelliteSystem: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.SatelliteSystem: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.SatelliteSystem: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.SatelliteSystem: ...
        def __rand__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.SatelliteSystem: ...
        def __rmul__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.SatelliteSystem: ...
        def __ror__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.SatelliteSystem: ...
        def __rsub__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.SatelliteSystem: ...
        def __rxor__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.SatelliteSystem: ...
        def __sub__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.SatelliteSystem: ...
        def __xor__(self, other: typing.SupportsInt) -> QGeoSatelliteInfo.SatelliteSystem: ...
    Azimuth: ClassVar[QGeoSatelliteInfo.Attribute] = ...
    Elevation: ClassVar[QGeoSatelliteInfo.Attribute] = ...
    GLONASS: ClassVar[QGeoSatelliteInfo.SatelliteSystem] = ...
    GPS: ClassVar[QGeoSatelliteInfo.SatelliteSystem] = ...
    Undefined: ClassVar[QGeoSatelliteInfo.SatelliteSystem] = ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, other: QGeoSatelliteInfo) -> None: ...
    def attribute(self, attribute: QGeoSatelliteInfo.Attribute) -> float: ...
    def hasAttribute(self, attribute: QGeoSatelliteInfo.Attribute) -> bool: ...
    def removeAttribute(self, attribute: QGeoSatelliteInfo.Attribute) -> None: ...
    def satelliteIdentifier(self) -> int: ...
    def satelliteSystem(self) -> QGeoSatelliteInfo.SatelliteSystem: ...
    def setAttribute(self, attribute: QGeoSatelliteInfo.Attribute, value: float) -> None: ...
    def setSatelliteIdentifier(self, satId: int) -> None: ...
    def setSatelliteSystem(self, system: QGeoSatelliteInfo.SatelliteSystem) -> None: ...
    def setSignalStrength(self, signalStrength: int) -> None: ...
    def signalStrength(self) -> int: ...
    def __copy__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lshift__(self, stream: PySide2.QtCore.QDataStream) -> PySide2.QtCore.QDataStream: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __rlshift__(self, other) -> Any: ...
    def __rrshift__(self, other) -> Any: ...
    def __rshift__(self, stream: PySide2.QtCore.QDataStream) -> PySide2.QtCore.QDataStream: ...

class QGeoSatelliteInfoSource(PySide2.QtCore.QObject):
    class Error:
        AccessError: ClassVar[QGeoSatelliteInfoSource.Error] = ...
        ClosedError: ClassVar[QGeoSatelliteInfoSource.Error] = ...
        NoError: ClassVar[QGeoSatelliteInfoSource.Error] = ...
        UnknownSourceError: ClassVar[QGeoSatelliteInfoSource.Error] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QGeoSatelliteInfoSource.Error: ...
        def __and__(self, other: typing.SupportsInt) -> QGeoSatelliteInfoSource.Error: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QGeoSatelliteInfoSource.Error: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QGeoSatelliteInfoSource.Error: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QGeoSatelliteInfoSource.Error: ...
        def __rand__(self, other: typing.SupportsInt) -> QGeoSatelliteInfoSource.Error: ...
        def __rmul__(self, other: typing.SupportsInt) -> QGeoSatelliteInfoSource.Error: ...
        def __ror__(self, other: typing.SupportsInt) -> QGeoSatelliteInfoSource.Error: ...
        def __rsub__(self, other: typing.SupportsInt) -> QGeoSatelliteInfoSource.Error: ...
        def __rxor__(self, other: typing.SupportsInt) -> QGeoSatelliteInfoSource.Error: ...
        def __sub__(self, other: typing.SupportsInt) -> QGeoSatelliteInfoSource.Error: ...
        def __xor__(self, other: typing.SupportsInt) -> QGeoSatelliteInfoSource.Error: ...
    AccessError: ClassVar[QGeoSatelliteInfoSource.Error] = ...
    ClosedError: ClassVar[QGeoSatelliteInfoSource.Error] = ...
    NoError: ClassVar[QGeoSatelliteInfoSource.Error] = ...
    UnknownSourceError: ClassVar[QGeoSatelliteInfoSource.Error] = ...
    error: ClassVar[PySide2.QtCore.Signal] = ...
    requestTimeout: ClassVar[PySide2.QtCore.Signal] = ...
    satellitesInUseUpdated: ClassVar[PySide2.QtCore.Signal] = ...
    satellitesInViewUpdated: ClassVar[PySide2.QtCore.Signal] = ...
    staticMetaObject: ClassVar[PySide2.QtCore.QMetaObject] = ...
    def __init__(self, parent: typing.Optional[PySide2.QtCore.QObject], destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    @classmethod
    def availableSources(cls) -> typing.List[str]: ...
    @classmethod
    @overload
    def createDefaultSource(cls, parameters: typing.Dict[str,typing.Any], parent: typing.Optional[PySide2.QtCore.QObject]) -> QGeoSatelliteInfoSource: ...
    @classmethod
    @overload
    def createDefaultSource(cls, parent: typing.Optional[PySide2.QtCore.QObject]) -> QGeoSatelliteInfoSource: ...
    @classmethod
    @overload
    def createSource(cls, sourceName: str, parameters: typing.Dict[str,typing.Any], parent: typing.Optional[PySide2.QtCore.QObject]) -> QGeoSatelliteInfoSource: ...
    @classmethod
    @overload
    def createSource(cls, sourceName: str, parent: typing.Optional[PySide2.QtCore.QObject]) -> QGeoSatelliteInfoSource: ...
    def minimumUpdateInterval(self) -> int: ...
    def requestUpdate(self, timeout: int = ...) -> None: ...
    def setUpdateInterval(self, msec: int) -> None: ...
    def sourceName(self) -> str: ...
    def startUpdates(self) -> None: ...
    def stopUpdates(self) -> None: ...
    def updateInterval(self) -> int: ...

class QGeoShape(shiboken2.Object):
    class ShapeType:
        CircleType: ClassVar[QGeoShape.ShapeType] = ...
        PathType: ClassVar[QGeoShape.ShapeType] = ...
        PolygonType: ClassVar[QGeoShape.ShapeType] = ...
        RectangleType: ClassVar[QGeoShape.ShapeType] = ...
        UnknownType: ClassVar[QGeoShape.ShapeType] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QGeoShape.ShapeType: ...
        def __and__(self, other: typing.SupportsInt) -> QGeoShape.ShapeType: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QGeoShape.ShapeType: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QGeoShape.ShapeType: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QGeoShape.ShapeType: ...
        def __rand__(self, other: typing.SupportsInt) -> QGeoShape.ShapeType: ...
        def __rmul__(self, other: typing.SupportsInt) -> QGeoShape.ShapeType: ...
        def __ror__(self, other: typing.SupportsInt) -> QGeoShape.ShapeType: ...
        def __rsub__(self, other: typing.SupportsInt) -> QGeoShape.ShapeType: ...
        def __rxor__(self, other: typing.SupportsInt) -> QGeoShape.ShapeType: ...
        def __sub__(self, other: typing.SupportsInt) -> QGeoShape.ShapeType: ...
        def __xor__(self, other: typing.SupportsInt) -> QGeoShape.ShapeType: ...
    CircleType: ClassVar[QGeoShape.ShapeType] = ...
    PathType: ClassVar[QGeoShape.ShapeType] = ...
    PolygonType: ClassVar[QGeoShape.ShapeType] = ...
    RectangleType: ClassVar[QGeoShape.ShapeType] = ...
    UnknownType: ClassVar[QGeoShape.ShapeType] = ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, other: QGeoShape) -> None: ...
    def boundingGeoRectangle(self) -> QGeoRectangle: ...
    def center(self) -> QGeoCoordinate: ...
    def contains(self, coordinate: QGeoCoordinate) -> bool: ...
    def extendShape(self, coordinate: QGeoCoordinate) -> None: ...
    def isEmpty(self) -> bool: ...
    def isValid(self) -> bool: ...
    def toString(self) -> str: ...
    def type(self) -> QGeoShape.ShapeType: ...
    def __copy__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lshift__(self, stream: PySide2.QtCore.QDataStream) -> PySide2.QtCore.QDataStream: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __rlshift__(self, other) -> Any: ...
    def __rrshift__(self, other) -> Any: ...
    def __rshift__(self, stream: PySide2.QtCore.QDataStream) -> PySide2.QtCore.QDataStream: ...

class QNmeaPositionInfoSource(QGeoPositionInfoSource):
    class UpdateMode:
        RealTimeMode: ClassVar[QNmeaPositionInfoSource.UpdateMode] = ...
        SimulationMode: ClassVar[QNmeaPositionInfoSource.UpdateMode] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QNmeaPositionInfoSource.UpdateMode: ...
        def __and__(self, other: typing.SupportsInt) -> QNmeaPositionInfoSource.UpdateMode: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QNmeaPositionInfoSource.UpdateMode: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QNmeaPositionInfoSource.UpdateMode: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QNmeaPositionInfoSource.UpdateMode: ...
        def __rand__(self, other: typing.SupportsInt) -> QNmeaPositionInfoSource.UpdateMode: ...
        def __rmul__(self, other: typing.SupportsInt) -> QNmeaPositionInfoSource.UpdateMode: ...
        def __ror__(self, other: typing.SupportsInt) -> QNmeaPositionInfoSource.UpdateMode: ...
        def __rsub__(self, other: typing.SupportsInt) -> QNmeaPositionInfoSource.UpdateMode: ...
        def __rxor__(self, other: typing.SupportsInt) -> QNmeaPositionInfoSource.UpdateMode: ...
        def __sub__(self, other: typing.SupportsInt) -> QNmeaPositionInfoSource.UpdateMode: ...
        def __xor__(self, other: typing.SupportsInt) -> QNmeaPositionInfoSource.UpdateMode: ...
    RealTimeMode: ClassVar[QNmeaPositionInfoSource.UpdateMode] = ...
    SimulationMode: ClassVar[QNmeaPositionInfoSource.UpdateMode] = ...
    staticMetaObject: ClassVar[PySide2.QtCore.QMetaObject] = ...
    def __init__(self, updateMode: QNmeaPositionInfoSource.UpdateMode, parent: typing.Union[PySide2.QtCore.QObject,None] = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def device(self) -> PySide2.QtCore.QIODevice: ...
    def error(self) -> QGeoPositionInfoSource.Error: ...
    def lastKnownPosition(self, fromSatellitePositioningMethodsOnly: bool = ...) -> QGeoPositionInfo: ...
    def minimumUpdateInterval(self) -> int: ...
    def parsePosInfoFromNmeaData(self, data: bytes, size: int, posInfo: QGeoPositionInfo) -> typing.Tuple[bool,bool]: ...
    def requestUpdate(self, timeout: int = ...) -> None: ...
    def setDevice(self, source: PySide2.QtCore.QIODevice) -> None: ...
    def setUpdateInterval(self, msec: int) -> None: ...
    def setUserEquivalentRangeError(self, uere: float) -> None: ...
    def startUpdates(self) -> None: ...
    def stopUpdates(self) -> None: ...
    def supportedPositioningMethods(self) -> typing.Union[QGeoPositionInfoSource.PositioningMethods,QGeoPositionInfoSource.PositioningMethod]: ...
    def updateMode(self) -> QNmeaPositionInfoSource.UpdateMode: ...
    def userEquivalentRangeError(self) -> float: ...
