from typing import Any, Callable, ClassVar, List, Optional, Tuple, Union

from typing import overload
import PySide2.QtCore
import shiboken2
import typing
T = typing.TypeVar('T')

class QScriptClass(shiboken2.Object):
    class Extension:
        Callable: ClassVar[QScriptClass.Extension] = ...
        HasInstance: ClassVar[QScriptClass.Extension] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QScriptClass.Extension: ...
        def __and__(self, other: typing.SupportsInt) -> QScriptClass.Extension: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QScriptClass.Extension: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QScriptClass.Extension: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QScriptClass.Extension: ...
        def __rand__(self, other: typing.SupportsInt) -> QScriptClass.Extension: ...
        def __rmul__(self, other: typing.SupportsInt) -> QScriptClass.Extension: ...
        def __ror__(self, other: typing.SupportsInt) -> QScriptClass.Extension: ...
        def __rsub__(self, other: typing.SupportsInt) -> QScriptClass.Extension: ...
        def __rxor__(self, other: typing.SupportsInt) -> QScriptClass.Extension: ...
        def __sub__(self, other: typing.SupportsInt) -> QScriptClass.Extension: ...
        def __xor__(self, other: typing.SupportsInt) -> QScriptClass.Extension: ...

    class QueryFlag:
        HandlesReadAccess: ClassVar[QScriptClass.QueryFlag] = ...
        HandlesWriteAccess: ClassVar[QScriptClass.QueryFlag] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QScriptClass.QueryFlag: ...
        def __and__(self, other: typing.SupportsInt) -> QScriptClass.QueryFlag: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QScriptClass.QueryFlag: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QScriptClass.QueryFlag: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QScriptClass.QueryFlag: ...
        def __rand__(self, other: typing.SupportsInt) -> QScriptClass.QueryFlag: ...
        def __rmul__(self, other: typing.SupportsInt) -> QScriptClass.QueryFlag: ...
        def __ror__(self, other: typing.SupportsInt) -> QScriptClass.QueryFlag: ...
        def __rsub__(self, other: typing.SupportsInt) -> QScriptClass.QueryFlag: ...
        def __rxor__(self, other: typing.SupportsInt) -> QScriptClass.QueryFlag: ...
        def __sub__(self, other: typing.SupportsInt) -> QScriptClass.QueryFlag: ...
        def __xor__(self, other: typing.SupportsInt) -> QScriptClass.QueryFlag: ...
    Callable: ClassVar[QScriptClass.Extension] = ...
    HandlesReadAccess: ClassVar[QScriptClass.QueryFlag] = ...
    HandlesWriteAccess: ClassVar[QScriptClass.QueryFlag] = ...
    HasInstance: ClassVar[QScriptClass.Extension] = ...
    def __init__(self, engine: QScriptEngine) -> None: ...
    def engine(self) -> QScriptEngine: ...
    def extension(self, extension: QScriptClass.Extension, argument: typing.Any = ...) -> typing.Any: ...
    def name(self) -> str: ...
    def newIterator(self, object: QScriptValue) -> QScriptClassPropertyIterator: ...
    def property(self, object: QScriptValue, name: QScriptString, id: int) -> QScriptValue: ...
    def propertyFlags(self, object: QScriptValue, name: QScriptString, id: int) -> typing.Union[QScriptValue.PropertyFlags,QScriptValue.PropertyFlag]: ...
    def prototype(self) -> QScriptValue: ...
    def setProperty(self, object: QScriptValue, name: QScriptString, id: int, value: QScriptValue) -> None: ...
    def supportsExtension(self, extension: QScriptClass.Extension) -> bool: ...

class QScriptClassPropertyIterator(shiboken2.Object):
    def __init__(self, object: QScriptValue) -> None: ...
    def flags(self) -> typing.Union[QScriptValue.PropertyFlags,QScriptValue.PropertyFlag]: ...
    def hasNext(self) -> bool: ...
    def hasPrevious(self) -> bool: ...
    def id(self) -> int: ...
    def name(self) -> QScriptString: ...
    def next(self) -> None: ...
    def object(self) -> QScriptValue: ...
    def previous(self) -> None: ...
    def toBack(self) -> None: ...
    def toFront(self) -> None: ...

class QScriptContext(shiboken2.Object):
    class Error:
        RangeError: ClassVar[QScriptContext.Error] = ...
        ReferenceError: ClassVar[QScriptContext.Error] = ...
        SyntaxError: ClassVar[QScriptContext.Error] = ...
        TypeError: ClassVar[QScriptContext.Error] = ...
        URIError: ClassVar[QScriptContext.Error] = ...
        UnknownError: ClassVar[QScriptContext.Error] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QScriptContext.Error: ...
        def __and__(self, other: typing.SupportsInt) -> QScriptContext.Error: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QScriptContext.Error: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QScriptContext.Error: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QScriptContext.Error: ...
        def __rand__(self, other: typing.SupportsInt) -> QScriptContext.Error: ...
        def __rmul__(self, other: typing.SupportsInt) -> QScriptContext.Error: ...
        def __ror__(self, other: typing.SupportsInt) -> QScriptContext.Error: ...
        def __rsub__(self, other: typing.SupportsInt) -> QScriptContext.Error: ...
        def __rxor__(self, other: typing.SupportsInt) -> QScriptContext.Error: ...
        def __sub__(self, other: typing.SupportsInt) -> QScriptContext.Error: ...
        def __xor__(self, other: typing.SupportsInt) -> QScriptContext.Error: ...

    class ExecutionState:
        ExceptionState: ClassVar[QScriptContext.ExecutionState] = ...
        NormalState: ClassVar[QScriptContext.ExecutionState] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QScriptContext.ExecutionState: ...
        def __and__(self, other: typing.SupportsInt) -> QScriptContext.ExecutionState: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QScriptContext.ExecutionState: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QScriptContext.ExecutionState: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QScriptContext.ExecutionState: ...
        def __rand__(self, other: typing.SupportsInt) -> QScriptContext.ExecutionState: ...
        def __rmul__(self, other: typing.SupportsInt) -> QScriptContext.ExecutionState: ...
        def __ror__(self, other: typing.SupportsInt) -> QScriptContext.ExecutionState: ...
        def __rsub__(self, other: typing.SupportsInt) -> QScriptContext.ExecutionState: ...
        def __rxor__(self, other: typing.SupportsInt) -> QScriptContext.ExecutionState: ...
        def __sub__(self, other: typing.SupportsInt) -> QScriptContext.ExecutionState: ...
        def __xor__(self, other: typing.SupportsInt) -> QScriptContext.ExecutionState: ...
    ExceptionState: ClassVar[QScriptContext.ExecutionState] = ...
    NormalState: ClassVar[QScriptContext.ExecutionState] = ...
    RangeError: ClassVar[QScriptContext.Error] = ...
    ReferenceError: ClassVar[QScriptContext.Error] = ...
    SyntaxError: ClassVar[QScriptContext.Error] = ...
    TypeError: ClassVar[QScriptContext.Error] = ...
    URIError: ClassVar[QScriptContext.Error] = ...
    UnknownError: ClassVar[QScriptContext.Error] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def activationObject(self) -> QScriptValue: ...
    def argument(self, index: int) -> QScriptValue: ...
    def argumentCount(self) -> int: ...
    def argumentsObject(self) -> QScriptValue: ...
    def backtrace(self) -> typing.List[str]: ...
    def callee(self) -> QScriptValue: ...
    def engine(self) -> QScriptEngine: ...
    def isCalledAsConstructor(self) -> bool: ...
    def parentContext(self) -> QScriptContext: ...
    def popScope(self) -> QScriptValue: ...
    def pushScope(self, object: QScriptValue) -> None: ...
    def returnValue(self) -> QScriptValue: ...
    def scopeChain(self) -> typing.List[QScriptValue]: ...
    def setActivationObject(self, activation: QScriptValue) -> None: ...
    def setReturnValue(self, result: QScriptValue) -> None: ...
    def setThisObject(self, thisObject: QScriptValue) -> None: ...
    def state(self) -> QScriptContext.ExecutionState: ...
    def thisObject(self) -> QScriptValue: ...
    @overload
    def throwError(self, error: QScriptContext.Error, text: str) -> QScriptValue: ...
    @overload
    def throwError(self, text: str) -> QScriptValue: ...
    def throwValue(self, value: QScriptValue) -> QScriptValue: ...
    def toString(self) -> str: ...

class QScriptContextInfo(shiboken2.Object):
    class FunctionType:
        NativeFunction: ClassVar[QScriptContextInfo.FunctionType] = ...
        QtFunction: ClassVar[QScriptContextInfo.FunctionType] = ...
        QtPropertyFunction: ClassVar[QScriptContextInfo.FunctionType] = ...
        ScriptFunction: ClassVar[QScriptContextInfo.FunctionType] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QScriptContextInfo.FunctionType: ...
        def __and__(self, other: typing.SupportsInt) -> QScriptContextInfo.FunctionType: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QScriptContextInfo.FunctionType: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QScriptContextInfo.FunctionType: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QScriptContextInfo.FunctionType: ...
        def __rand__(self, other: typing.SupportsInt) -> QScriptContextInfo.FunctionType: ...
        def __rmul__(self, other: typing.SupportsInt) -> QScriptContextInfo.FunctionType: ...
        def __ror__(self, other: typing.SupportsInt) -> QScriptContextInfo.FunctionType: ...
        def __rsub__(self, other: typing.SupportsInt) -> QScriptContextInfo.FunctionType: ...
        def __rxor__(self, other: typing.SupportsInt) -> QScriptContextInfo.FunctionType: ...
        def __sub__(self, other: typing.SupportsInt) -> QScriptContextInfo.FunctionType: ...
        def __xor__(self, other: typing.SupportsInt) -> QScriptContextInfo.FunctionType: ...
    NativeFunction: ClassVar[QScriptContextInfo.FunctionType] = ...
    QtFunction: ClassVar[QScriptContextInfo.FunctionType] = ...
    QtPropertyFunction: ClassVar[QScriptContextInfo.FunctionType] = ...
    ScriptFunction: ClassVar[QScriptContextInfo.FunctionType] = ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, context: QScriptContext) -> None: ...
    @overload
    def __init__(self, other: QScriptContextInfo) -> None: ...
    def columnNumber(self) -> int: ...
    def fileName(self) -> str: ...
    def functionEndLineNumber(self) -> int: ...
    def functionMetaIndex(self) -> int: ...
    def functionName(self) -> str: ...
    def functionParameterNames(self) -> typing.List[str]: ...
    def functionStartLineNumber(self) -> int: ...
    def functionType(self) -> QScriptContextInfo.FunctionType: ...
    def isNull(self) -> bool: ...
    def lineNumber(self) -> int: ...
    def scriptId(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __copy__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lshift__(self, arg__1: PySide2.QtCore.QDataStream) -> PySide2.QtCore.QDataStream: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __rlshift__(self, other) -> Any: ...
    def __rrshift__(self, other) -> Any: ...
    def __rshift__(self, arg__1: PySide2.QtCore.QDataStream) -> PySide2.QtCore.QDataStream: ...

class QScriptEngine(PySide2.QtCore.QObject):
    class QObjectWrapOption:
        AutoCreateDynamicProperties: ClassVar[QScriptEngine.QObjectWrapOption] = ...
        ExcludeChildObjects: ClassVar[QScriptEngine.QObjectWrapOption] = ...
        ExcludeDeleteLater: ClassVar[QScriptEngine.QObjectWrapOption] = ...
        ExcludeSlots: ClassVar[QScriptEngine.QObjectWrapOption] = ...
        ExcludeSuperClassContents: ClassVar[QScriptEngine.QObjectWrapOption] = ...
        ExcludeSuperClassMethods: ClassVar[QScriptEngine.QObjectWrapOption] = ...
        ExcludeSuperClassProperties: ClassVar[QScriptEngine.QObjectWrapOption] = ...
        PreferExistingWrapperObject: ClassVar[QScriptEngine.QObjectWrapOption] = ...
        SkipMethodsInEnumeration: ClassVar[QScriptEngine.QObjectWrapOption] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __and__(self, other: typing.SupportsInt) -> QScriptEngine.QObjectWrapOptions: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __invert__(self) -> QScriptEngine.QObjectWrapOption: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QScriptEngine.QObjectWrapOptions: ...
        def __rand__(self, other: typing.SupportsInt) -> QScriptEngine.QObjectWrapOptions: ...
        def __ror__(self, other: typing.SupportsInt) -> QScriptEngine.QObjectWrapOptions: ...
        def __rxor__(self, other: typing.SupportsInt) -> QScriptEngine.QObjectWrapOptions: ...
        def __xor__(self, other: typing.SupportsInt) -> QScriptEngine.QObjectWrapOptions: ...

    class QObjectWrapOptions:
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __and__(self, other: typing.SupportsInt) -> QScriptEngine.QObjectWrapOptions: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __invert__(self) -> QScriptEngine.QObjectWrapOptions: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QScriptEngine.QObjectWrapOptions: ...
        def __rand__(self, other: typing.SupportsInt) -> QScriptEngine.QObjectWrapOptions: ...
        def __ror__(self, other: typing.SupportsInt) -> QScriptEngine.QObjectWrapOptions: ...
        def __rxor__(self, other: typing.SupportsInt) -> QScriptEngine.QObjectWrapOptions: ...
        def __xor__(self, other: typing.SupportsInt) -> QScriptEngine.QObjectWrapOptions: ...

    class ValueOwnership:
        AutoOwnership: ClassVar[QScriptEngine.ValueOwnership] = ...
        QtOwnership: ClassVar[QScriptEngine.ValueOwnership] = ...
        ScriptOwnership: ClassVar[QScriptEngine.ValueOwnership] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QScriptEngine.ValueOwnership: ...
        def __and__(self, other: typing.SupportsInt) -> QScriptEngine.ValueOwnership: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QScriptEngine.ValueOwnership: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QScriptEngine.ValueOwnership: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QScriptEngine.ValueOwnership: ...
        def __rand__(self, other: typing.SupportsInt) -> QScriptEngine.ValueOwnership: ...
        def __rmul__(self, other: typing.SupportsInt) -> QScriptEngine.ValueOwnership: ...
        def __ror__(self, other: typing.SupportsInt) -> QScriptEngine.ValueOwnership: ...
        def __rsub__(self, other: typing.SupportsInt) -> QScriptEngine.ValueOwnership: ...
        def __rxor__(self, other: typing.SupportsInt) -> QScriptEngine.ValueOwnership: ...
        def __sub__(self, other: typing.SupportsInt) -> QScriptEngine.ValueOwnership: ...
        def __xor__(self, other: typing.SupportsInt) -> QScriptEngine.ValueOwnership: ...
    AutoCreateDynamicProperties: ClassVar[QScriptEngine.QObjectWrapOption] = ...
    AutoOwnership: ClassVar[QScriptEngine.ValueOwnership] = ...
    ExcludeChildObjects: ClassVar[QScriptEngine.QObjectWrapOption] = ...
    ExcludeDeleteLater: ClassVar[QScriptEngine.QObjectWrapOption] = ...
    ExcludeSlots: ClassVar[QScriptEngine.QObjectWrapOption] = ...
    ExcludeSuperClassContents: ClassVar[QScriptEngine.QObjectWrapOption] = ...
    ExcludeSuperClassMethods: ClassVar[QScriptEngine.QObjectWrapOption] = ...
    ExcludeSuperClassProperties: ClassVar[QScriptEngine.QObjectWrapOption] = ...
    PreferExistingWrapperObject: ClassVar[QScriptEngine.QObjectWrapOption] = ...
    QtOwnership: ClassVar[QScriptEngine.ValueOwnership] = ...
    ScriptOwnership: ClassVar[QScriptEngine.ValueOwnership] = ...
    SkipMethodsInEnumeration: ClassVar[QScriptEngine.QObjectWrapOption] = ...
    signalHandlerException: ClassVar[PySide2.QtCore.Signal] = ...
    staticMetaObject: ClassVar[PySide2.QtCore.QMetaObject] = ...
    @overload
    def __init__(self, destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., signalHandlerException: typing.Callable = ...) -> None: ...
    @overload
    def __init__(self, parent: typing.Optional[PySide2.QtCore.QObject], destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ..., signalHandlerException: typing.Callable = ...) -> None: ...
    def abortEvaluation(self, result: QScriptValue = ...) -> None: ...
    def agent(self) -> QScriptEngineAgent: ...
    def availableExtensions(self) -> typing.List[str]: ...
    def canEvaluate(self, program: str) -> bool: ...
    def clearExceptions(self) -> None: ...
    def collectGarbage(self) -> None: ...
    def currentContext(self) -> QScriptContext: ...
    def defaultPrototype(self, metaTypeId: int) -> QScriptValue: ...
    @overload
    def evaluate(self, program: QScriptProgram) -> QScriptValue: ...
    @overload
    def evaluate(self, program: str, fileName: str = ..., lineNumber: int = ...) -> QScriptValue: ...
    def globalObject(self) -> QScriptValue: ...
    def hasUncaughtException(self) -> bool: ...
    def importExtension(self, extension: str) -> QScriptValue: ...
    def importedExtensions(self) -> typing.List[str]: ...
    def installTranslatorFunctions(self, object: QScriptValue = ...) -> None: ...
    def isEvaluating(self) -> bool: ...
    def newActivationObject(self) -> QScriptValue: ...
    def newArray(self, length: int = ...) -> QScriptValue: ...
    @overload
    def newDate(self, value: PySide2.QtCore.QDateTime) -> QScriptValue: ...
    @overload
    def newDate(self, value: float) -> QScriptValue: ...
    @overload
    def newObject(self) -> QScriptValue: ...
    @overload
    def newObject(self, scriptClass: QScriptClass, data: QScriptValue = ...) -> QScriptValue: ...
    def newQMetaObject(self, metaObject: PySide2.QtCore.QMetaObject, ctor: QScriptValue = ...) -> QScriptValue: ...
    @overload
    def newQObject(self, object: PySide2.QtCore.QObject, ownership: QScriptEngine.ValueOwnership = ..., options: typing.Union[QScriptEngine.QObjectWrapOptions,QScriptEngine.QObjectWrapOption] = ...) -> QScriptValue: ...
    @overload
    def newQObject(self, scriptObject: QScriptValue, qtObject: PySide2.QtCore.QObject, ownership: QScriptEngine.ValueOwnership = ..., options: typing.Union[QScriptEngine.QObjectWrapOptions,QScriptEngine.QObjectWrapOption] = ...) -> QScriptValue: ...
    @overload
    def newRegExp(self, pattern: str, flags: str) -> QScriptValue: ...
    @overload
    def newRegExp(self, regexp: PySide2.QtCore.QRegExp) -> QScriptValue: ...
    @overload
    def newVariant(self, object: QScriptValue, value: typing.Any) -> QScriptValue: ...
    @overload
    def newVariant(self, value: typing.Any) -> QScriptValue: ...
    def nullValue(self) -> QScriptValue: ...
    def objectById(self, id: int) -> QScriptValue: ...
    def popContext(self) -> None: ...
    def processEventsInterval(self) -> int: ...
    def pushContext(self) -> QScriptContext: ...
    def reportAdditionalMemoryCost(self, size: int) -> None: ...
    def setAgent(self, agent: QScriptEngineAgent) -> None: ...
    def setDefaultPrototype(self, metaTypeId: int, prototype: QScriptValue) -> None: ...
    def setGlobalObject(self, object: QScriptValue) -> None: ...
    def setProcessEventsInterval(self, interval: int) -> None: ...
    def toObject(self, value: QScriptValue) -> QScriptValue: ...
    def toStringHandle(self, str: str) -> QScriptString: ...
    def uncaughtException(self) -> QScriptValue: ...
    def uncaughtExceptionBacktrace(self) -> typing.List[str]: ...
    def uncaughtExceptionLineNumber(self) -> int: ...
    def undefinedValue(self) -> QScriptValue: ...

class QScriptEngineAgent(shiboken2.Object):
    class Extension:
        DebuggerInvocationRequest: ClassVar[QScriptEngineAgent.Extension] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QScriptEngineAgent.Extension: ...
        def __and__(self, other: typing.SupportsInt) -> QScriptEngineAgent.Extension: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QScriptEngineAgent.Extension: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QScriptEngineAgent.Extension: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QScriptEngineAgent.Extension: ...
        def __rand__(self, other: typing.SupportsInt) -> QScriptEngineAgent.Extension: ...
        def __rmul__(self, other: typing.SupportsInt) -> QScriptEngineAgent.Extension: ...
        def __ror__(self, other: typing.SupportsInt) -> QScriptEngineAgent.Extension: ...
        def __rsub__(self, other: typing.SupportsInt) -> QScriptEngineAgent.Extension: ...
        def __rxor__(self, other: typing.SupportsInt) -> QScriptEngineAgent.Extension: ...
        def __sub__(self, other: typing.SupportsInt) -> QScriptEngineAgent.Extension: ...
        def __xor__(self, other: typing.SupportsInt) -> QScriptEngineAgent.Extension: ...
    DebuggerInvocationRequest: ClassVar[QScriptEngineAgent.Extension] = ...
    def __init__(self, engine: QScriptEngine) -> None: ...
    def contextPop(self) -> None: ...
    def contextPush(self) -> None: ...
    def engine(self) -> QScriptEngine: ...
    def exceptionCatch(self, scriptId: int, exception: QScriptValue) -> None: ...
    def exceptionThrow(self, scriptId: int, exception: QScriptValue, hasHandler: bool) -> None: ...
    def extension(self, extension: QScriptEngineAgent.Extension, argument: typing.Any = ...) -> typing.Any: ...
    def functionEntry(self, scriptId: int) -> None: ...
    def functionExit(self, scriptId: int, returnValue: QScriptValue) -> None: ...
    def positionChange(self, scriptId: int, lineNumber: int, columnNumber: int) -> None: ...
    def scriptLoad(self, id: int, program: str, fileName: str, baseLineNumber: int) -> None: ...
    def scriptUnload(self, id: int) -> None: ...
    def supportsExtension(self, extension: QScriptEngineAgent.Extension) -> bool: ...

class QScriptExtensionInterface(PySide2.QtCore.QFactoryInterface):
    def __init__(self) -> None: ...
    def initialize(self, key: str, engine: QScriptEngine) -> None: ...

class QScriptExtensionPlugin(PySide2.QtCore.QObject, QScriptExtensionInterface):
    staticMetaObject: ClassVar[PySide2.QtCore.QMetaObject] = ...
    def __init__(self, parent: typing.Union[PySide2.QtCore.QObject,None] = ..., destroyed: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def initialize(self, key: str, engine: QScriptEngine) -> None: ...
    def keys(self) -> typing.List[str]: ...
    def setupPackage(self, key: str, engine: QScriptEngine) -> QScriptValue: ...

class QScriptProgram(shiboken2.Object):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, other: QScriptProgram) -> None: ...
    @overload
    def __init__(self, sourceCode: str, fileName: str = ..., firstLineNumber: int = ...) -> None: ...
    def fileName(self) -> str: ...
    def firstLineNumber(self) -> int: ...
    def isNull(self) -> bool: ...
    def sourceCode(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __copy__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QScriptString(shiboken2.Object):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, other: QScriptString) -> None: ...
    def isValid(self) -> bool: ...
    def toArrayIndex(self) -> typing.Tuple[int,bool]: ...
    def toString(self) -> str: ...
    def __copy__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class QScriptValue(shiboken2.Object):
    class PropertyFlag:
        KeepExistingFlags: ClassVar[QScriptValue.PropertyFlag] = ...
        PropertyGetter: ClassVar[QScriptValue.PropertyFlag] = ...
        PropertySetter: ClassVar[QScriptValue.PropertyFlag] = ...
        QObjectMember: ClassVar[QScriptValue.PropertyFlag] = ...
        ReadOnly: ClassVar[QScriptValue.PropertyFlag] = ...
        SkipInEnumeration: ClassVar[QScriptValue.PropertyFlag] = ...
        Undeletable: ClassVar[QScriptValue.PropertyFlag] = ...
        UserRange: ClassVar[QScriptValue.PropertyFlag] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __and__(self, other: typing.SupportsInt) -> QScriptValue.PropertyFlags: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __invert__(self) -> QScriptValue.PropertyFlag: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QScriptValue.PropertyFlags: ...
        def __rand__(self, other: typing.SupportsInt) -> QScriptValue.PropertyFlags: ...
        def __ror__(self, other: typing.SupportsInt) -> QScriptValue.PropertyFlags: ...
        def __rxor__(self, other: typing.SupportsInt) -> QScriptValue.PropertyFlags: ...
        def __xor__(self, other: typing.SupportsInt) -> QScriptValue.PropertyFlags: ...

    class PropertyFlags:
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __and__(self, other: typing.SupportsInt) -> QScriptValue.PropertyFlags: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __invert__(self) -> QScriptValue.PropertyFlags: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QScriptValue.PropertyFlags: ...
        def __rand__(self, other: typing.SupportsInt) -> QScriptValue.PropertyFlags: ...
        def __ror__(self, other: typing.SupportsInt) -> QScriptValue.PropertyFlags: ...
        def __rxor__(self, other: typing.SupportsInt) -> QScriptValue.PropertyFlags: ...
        def __xor__(self, other: typing.SupportsInt) -> QScriptValue.PropertyFlags: ...

    class ResolveFlag:
        ResolveFull: ClassVar[QScriptValue.ResolveFlag] = ...
        ResolveLocal: ClassVar[QScriptValue.ResolveFlag] = ...
        ResolvePrototype: ClassVar[QScriptValue.ResolveFlag] = ...
        ResolveScope: ClassVar[QScriptValue.ResolveFlag] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __and__(self, other: typing.SupportsInt) -> QScriptValue.ResolveFlags: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __invert__(self) -> QScriptValue.ResolveFlag: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QScriptValue.ResolveFlags: ...
        def __rand__(self, other: typing.SupportsInt) -> QScriptValue.ResolveFlags: ...
        def __ror__(self, other: typing.SupportsInt) -> QScriptValue.ResolveFlags: ...
        def __rxor__(self, other: typing.SupportsInt) -> QScriptValue.ResolveFlags: ...
        def __xor__(self, other: typing.SupportsInt) -> QScriptValue.ResolveFlags: ...

    class ResolveFlags:
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __and__(self, other: typing.SupportsInt) -> QScriptValue.ResolveFlags: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __invert__(self) -> QScriptValue.ResolveFlags: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QScriptValue.ResolveFlags: ...
        def __rand__(self, other: typing.SupportsInt) -> QScriptValue.ResolveFlags: ...
        def __ror__(self, other: typing.SupportsInt) -> QScriptValue.ResolveFlags: ...
        def __rxor__(self, other: typing.SupportsInt) -> QScriptValue.ResolveFlags: ...
        def __xor__(self, other: typing.SupportsInt) -> QScriptValue.ResolveFlags: ...

    class SpecialValue:
        NullValue: ClassVar[QScriptValue.SpecialValue] = ...
        UndefinedValue: ClassVar[QScriptValue.SpecialValue] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QScriptValue.SpecialValue: ...
        def __and__(self, other: typing.SupportsInt) -> QScriptValue.SpecialValue: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QScriptValue.SpecialValue: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QScriptValue.SpecialValue: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QScriptValue.SpecialValue: ...
        def __rand__(self, other: typing.SupportsInt) -> QScriptValue.SpecialValue: ...
        def __rmul__(self, other: typing.SupportsInt) -> QScriptValue.SpecialValue: ...
        def __ror__(self, other: typing.SupportsInt) -> QScriptValue.SpecialValue: ...
        def __rsub__(self, other: typing.SupportsInt) -> QScriptValue.SpecialValue: ...
        def __rxor__(self, other: typing.SupportsInt) -> QScriptValue.SpecialValue: ...
        def __sub__(self, other: typing.SupportsInt) -> QScriptValue.SpecialValue: ...
        def __xor__(self, other: typing.SupportsInt) -> QScriptValue.SpecialValue: ...
    KeepExistingFlags: ClassVar[QScriptValue.PropertyFlag] = ...
    NullValue: ClassVar[QScriptValue.SpecialValue] = ...
    PropertyGetter: ClassVar[QScriptValue.PropertyFlag] = ...
    PropertySetter: ClassVar[QScriptValue.PropertyFlag] = ...
    QObjectMember: ClassVar[QScriptValue.PropertyFlag] = ...
    ReadOnly: ClassVar[QScriptValue.PropertyFlag] = ...
    ResolveFull: ClassVar[QScriptValue.ResolveFlag] = ...
    ResolveLocal: ClassVar[QScriptValue.ResolveFlag] = ...
    ResolvePrototype: ClassVar[QScriptValue.ResolveFlag] = ...
    ResolveScope: ClassVar[QScriptValue.ResolveFlag] = ...
    SkipInEnumeration: ClassVar[QScriptValue.PropertyFlag] = ...
    UndefinedValue: ClassVar[QScriptValue.SpecialValue] = ...
    Undeletable: ClassVar[QScriptValue.PropertyFlag] = ...
    UserRange: ClassVar[QScriptValue.PropertyFlag] = ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, engine: QScriptEngine, val: QScriptValue.SpecialValue) -> None: ...
    @overload
    def __init__(self, engine: QScriptEngine, val: str) -> None: ...
    @overload
    def __init__(self, engine: QScriptEngine, val: bool) -> None: ...
    @overload
    def __init__(self, engine: QScriptEngine, val: bytes) -> None: ...
    @overload
    def __init__(self, engine: QScriptEngine, val: float) -> None: ...
    @overload
    def __init__(self, engine: QScriptEngine, val: int) -> None: ...
    @overload
    def __init__(self, other: QScriptValue) -> None: ...
    @overload
    def __init__(self, value: QScriptValue.SpecialValue) -> None: ...
    @overload
    def __init__(self, value: str) -> None: ...
    @overload
    def __init__(self, value: bool) -> None: ...
    @overload
    def __init__(self, value: bytes) -> None: ...
    @overload
    def __init__(self, value: float) -> None: ...
    @overload
    def __init__(self, value: int) -> None: ...
    @overload
    def call(self, thisObject: QScriptValue, arguments: QScriptValue) -> QScriptValue: ...
    @overload
    def call(self, thisObject: QScriptValue = ..., args: typing.Sequence[QScriptValue] = ...) -> QScriptValue: ...
    @overload
    def construct(self, args: typing.Sequence[QScriptValue] = ...) -> QScriptValue: ...
    @overload
    def construct(self, arguments: QScriptValue) -> QScriptValue: ...
    def data(self) -> QScriptValue: ...
    def engine(self) -> QScriptEngine: ...
    def equals(self, other: QScriptValue) -> bool: ...
    def instanceOf(self, other: QScriptValue) -> bool: ...
    def isArray(self) -> bool: ...
    def isBool(self) -> bool: ...
    def isBoolean(self) -> bool: ...
    def isDate(self) -> bool: ...
    def isError(self) -> bool: ...
    def isFunction(self) -> bool: ...
    def isNull(self) -> bool: ...
    def isNumber(self) -> bool: ...
    def isObject(self) -> bool: ...
    def isQMetaObject(self) -> bool: ...
    def isQObject(self) -> bool: ...
    def isRegExp(self) -> bool: ...
    def isString(self) -> bool: ...
    def isUndefined(self) -> bool: ...
    def isValid(self) -> bool: ...
    def isVariant(self) -> bool: ...
    def lessThan(self, other: QScriptValue) -> bool: ...
    def objectId(self) -> int: ...
    @overload
    def property(self, arrayIndex: int, mode: typing.Union[QScriptValue.ResolveFlags,QScriptValue.ResolveFlag] = ...) -> QScriptValue: ...
    @overload
    def property(self, name: QScriptString, mode: typing.Union[QScriptValue.ResolveFlags,QScriptValue.ResolveFlag] = ...) -> QScriptValue: ...
    @overload
    def property(self, name: str, mode: typing.Union[QScriptValue.ResolveFlags,QScriptValue.ResolveFlag] = ...) -> QScriptValue: ...
    @overload
    def propertyFlags(self, name: QScriptString, mode: typing.Union[QScriptValue.ResolveFlags,QScriptValue.ResolveFlag] = ...) -> typing.Union[QScriptValue.PropertyFlags,QScriptValue.PropertyFlag]: ...
    @overload
    def propertyFlags(self, name: str, mode: typing.Union[QScriptValue.ResolveFlags,QScriptValue.ResolveFlag] = ...) -> typing.Union[QScriptValue.PropertyFlags,QScriptValue.PropertyFlag]: ...
    def prototype(self) -> QScriptValue: ...
    def scope(self) -> QScriptValue: ...
    def scriptClass(self) -> QScriptClass: ...
    def setData(self, data: QScriptValue) -> None: ...
    @overload
    def setProperty(self, arrayIndex: int, value: QScriptValue, flags: typing.Union[QScriptValue.PropertyFlags,QScriptValue.PropertyFlag] = ...) -> None: ...
    @overload
    def setProperty(self, name: QScriptString, value: QScriptValue, flags: typing.Union[QScriptValue.PropertyFlags,QScriptValue.PropertyFlag] = ...) -> None: ...
    @overload
    def setProperty(self, name: str, value: QScriptValue, flags: typing.Union[QScriptValue.PropertyFlags,QScriptValue.PropertyFlag] = ...) -> None: ...
    def setPrototype(self, prototype: QScriptValue) -> None: ...
    def setScope(self, scope: QScriptValue) -> None: ...
    def setScriptClass(self, scriptClass: QScriptClass) -> None: ...
    def strictlyEquals(self, other: QScriptValue) -> bool: ...
    def toBool(self) -> bool: ...
    def toBoolean(self) -> bool: ...
    def toDateTime(self) -> PySide2.QtCore.QDateTime: ...
    def toInt32(self) -> int: ...
    def toInteger(self) -> float: ...
    def toNumber(self) -> float: ...
    def toObject(self) -> QScriptValue: ...
    def toQMetaObject(self) -> PySide2.QtCore.QMetaObject: ...
    def toQObject(self) -> PySide2.QtCore.QObject: ...
    def toRegExp(self) -> PySide2.QtCore.QRegExp: ...
    def toString(self) -> str: ...
    def toUInt16(self) -> int: ...
    def toUInt32(self) -> int: ...
    def toVariant(self) -> typing.Any: ...
    def __bool__(self) -> bool: ...
    def __copy__(self) -> None: ...
    def __getitem__(self, index) -> Any: ...
    def __iter__(self) -> object: ...

class QScriptValueIterator(shiboken2.Object):
    def __init__(self, value: QScriptValue) -> None: ...
    def flags(self) -> typing.Union[QScriptValue.PropertyFlags,QScriptValue.PropertyFlag]: ...
    def hasNext(self) -> bool: ...
    def hasPrevious(self) -> bool: ...
    def name(self) -> str: ...
    def next(self) -> None: ...
    def previous(self) -> None: ...
    def remove(self) -> None: ...
    def scriptName(self) -> QScriptString: ...
    def setValue(self, value: QScriptValue) -> None: ...
    def toBack(self) -> None: ...
    def toFront(self) -> None: ...
    def value(self) -> QScriptValue: ...
    def __iter__(self) -> object: ...
    def __next__(self) -> object: ...

class QScriptable(shiboken2.Object):
    def __init__(self) -> None: ...
    def argument(self, index: int) -> QScriptValue: ...
    def argumentCount(self) -> int: ...
    def context(self) -> QScriptContext: ...
    def engine(self) -> QScriptEngine: ...
    def thisObject(self) -> QScriptValue: ...
