from typing import Any, Callable, ClassVar, Union

import PySide2.QtCore
import PySide2.QtScript
import PySide2.QtWidgets
import typing
T = typing.TypeVar('T')

class QScriptEngineDebugger(PySide2.QtCore.QObject):
    class DebuggerAction:
        ClearConsoleAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
        ClearDebugOutputAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
        ClearErrorLogAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
        ContinueAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
        FindInScriptAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
        FindNextInScriptAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
        FindPreviousInScriptAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
        GoToLineAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
        InterruptAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
        RunToCursorAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
        RunToNewScriptAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
        StepIntoAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
        StepOutAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
        StepOverAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
        ToggleBreakpointAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerAction: ...
        def __and__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerAction: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerAction: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerAction: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerAction: ...
        def __rand__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerAction: ...
        def __rmul__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerAction: ...
        def __ror__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerAction: ...
        def __rsub__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerAction: ...
        def __rxor__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerAction: ...
        def __sub__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerAction: ...
        def __xor__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerAction: ...

    class DebuggerState:
        RunningState: ClassVar[QScriptEngineDebugger.DebuggerState] = ...
        SuspendedState: ClassVar[QScriptEngineDebugger.DebuggerState] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerState: ...
        def __and__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerState: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerState: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerState: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerState: ...
        def __rand__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerState: ...
        def __rmul__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerState: ...
        def __ror__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerState: ...
        def __rsub__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerState: ...
        def __rxor__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerState: ...
        def __sub__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerState: ...
        def __xor__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerState: ...

    class DebuggerWidget:
        BreakpointsWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
        CodeFinderWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
        CodeWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
        ConsoleWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
        DebugOutputWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
        ErrorLogWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
        LocalsWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
        ScriptsWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
        StackWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerWidget: ...
        def __and__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerWidget: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerWidget: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerWidget: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerWidget: ...
        def __rand__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerWidget: ...
        def __rmul__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerWidget: ...
        def __ror__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerWidget: ...
        def __rsub__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerWidget: ...
        def __rxor__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerWidget: ...
        def __sub__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerWidget: ...
        def __xor__(self, other: typing.SupportsInt) -> QScriptEngineDebugger.DebuggerWidget: ...
    BreakpointsWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
    ClearConsoleAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
    ClearDebugOutputAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
    ClearErrorLogAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
    CodeFinderWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
    CodeWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
    ConsoleWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
    ContinueAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
    DebugOutputWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
    ErrorLogWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
    FindInScriptAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
    FindNextInScriptAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
    FindPreviousInScriptAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
    GoToLineAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
    InterruptAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
    LocalsWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
    RunToCursorAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
    RunToNewScriptAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
    RunningState: ClassVar[QScriptEngineDebugger.DebuggerState] = ...
    ScriptsWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
    StackWidget: ClassVar[QScriptEngineDebugger.DebuggerWidget] = ...
    StepIntoAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
    StepOutAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
    StepOverAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
    SuspendedState: ClassVar[QScriptEngineDebugger.DebuggerState] = ...
    ToggleBreakpointAction: ClassVar[QScriptEngineDebugger.DebuggerAction] = ...
    evaluationResumed: ClassVar[PySide2.QtCore.Signal] = ...
    evaluationSuspended: ClassVar[PySide2.QtCore.Signal] = ...
    staticMetaObject: ClassVar[PySide2.QtCore.QMetaObject] = ...
    def __init__(self, parent: typing.Union[PySide2.QtCore.QObject,None] = ..., destroyed: typing.Callable = ..., evaluationResumed: typing.Callable = ..., evaluationSuspended: typing.Callable = ..., objectName: str = ..., objectNameChanged: typing.Callable = ...) -> None: ...
    def action(self, action: QScriptEngineDebugger.DebuggerAction) -> PySide2.QtWidgets.QAction: ...
    def attachTo(self, engine: PySide2.QtScript.QScriptEngine) -> None: ...
    def autoShowStandardWindow(self) -> bool: ...
    def createStandardMenu(self, parent: typing.Union[PySide2.QtWidgets.QWidget,None] = ...) -> PySide2.QtWidgets.QMenu: ...
    def createStandardToolBar(self, parent: typing.Union[PySide2.QtWidgets.QWidget,None] = ...) -> PySide2.QtWidgets.QToolBar: ...
    def setAutoShowStandardWindow(self, autoShow: bool) -> None: ...
    def standardWindow(self) -> PySide2.QtWidgets.QMainWindow: ...
    def state(self) -> QScriptEngineDebugger.DebuggerState: ...
    def widget(self, widget: QScriptEngineDebugger.DebuggerWidget) -> PySide2.QtWidgets.QWidget: ...
