from typing import Any, ClassVar, Union

from typing import overload
import PySide2.QtCore
import PySide2.QtGui
import PySide2.QtWidgets
import shiboken2
import typing
T = typing.TypeVar('T')

class QTest(shiboken2.Object):
    class KeyAction:
        Click: ClassVar[QTest.KeyAction] = ...
        Press: ClassVar[QTest.KeyAction] = ...
        Release: ClassVar[QTest.KeyAction] = ...
        Shortcut: ClassVar[QTest.KeyAction] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QTest.KeyAction: ...
        def __and__(self, other: typing.SupportsInt) -> QTest.KeyAction: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QTest.KeyAction: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QTest.KeyAction: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QTest.KeyAction: ...
        def __rand__(self, other: typing.SupportsInt) -> QTest.KeyAction: ...
        def __rmul__(self, other: typing.SupportsInt) -> QTest.KeyAction: ...
        def __ror__(self, other: typing.SupportsInt) -> QTest.KeyAction: ...
        def __rsub__(self, other: typing.SupportsInt) -> QTest.KeyAction: ...
        def __rxor__(self, other: typing.SupportsInt) -> QTest.KeyAction: ...
        def __sub__(self, other: typing.SupportsInt) -> QTest.KeyAction: ...
        def __xor__(self, other: typing.SupportsInt) -> QTest.KeyAction: ...

    class MouseAction:
        MouseClick: ClassVar[QTest.MouseAction] = ...
        MouseDClick: ClassVar[QTest.MouseAction] = ...
        MouseMove: ClassVar[QTest.MouseAction] = ...
        MousePress: ClassVar[QTest.MouseAction] = ...
        MouseRelease: ClassVar[QTest.MouseAction] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QTest.MouseAction: ...
        def __and__(self, other: typing.SupportsInt) -> QTest.MouseAction: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QTest.MouseAction: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QTest.MouseAction: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QTest.MouseAction: ...
        def __rand__(self, other: typing.SupportsInt) -> QTest.MouseAction: ...
        def __rmul__(self, other: typing.SupportsInt) -> QTest.MouseAction: ...
        def __ror__(self, other: typing.SupportsInt) -> QTest.MouseAction: ...
        def __rsub__(self, other: typing.SupportsInt) -> QTest.MouseAction: ...
        def __rxor__(self, other: typing.SupportsInt) -> QTest.MouseAction: ...
        def __sub__(self, other: typing.SupportsInt) -> QTest.MouseAction: ...
        def __xor__(self, other: typing.SupportsInt) -> QTest.MouseAction: ...

    class QBenchmarkMetric:
        AlignmentFaults: ClassVar[QTest.QBenchmarkMetric] = ...
        BitsPerSecond: ClassVar[QTest.QBenchmarkMetric] = ...
        BranchInstructions: ClassVar[QTest.QBenchmarkMetric] = ...
        BranchMisses: ClassVar[QTest.QBenchmarkMetric] = ...
        BusCycles: ClassVar[QTest.QBenchmarkMetric] = ...
        BytesAllocated: ClassVar[QTest.QBenchmarkMetric] = ...
        BytesPerSecond: ClassVar[QTest.QBenchmarkMetric] = ...
        CPUCycles: ClassVar[QTest.QBenchmarkMetric] = ...
        CPUMigrations: ClassVar[QTest.QBenchmarkMetric] = ...
        CPUTicks: ClassVar[QTest.QBenchmarkMetric] = ...
        CacheMisses: ClassVar[QTest.QBenchmarkMetric] = ...
        CachePrefetchMisses: ClassVar[QTest.QBenchmarkMetric] = ...
        CachePrefetches: ClassVar[QTest.QBenchmarkMetric] = ...
        CacheReadMisses: ClassVar[QTest.QBenchmarkMetric] = ...
        CacheReads: ClassVar[QTest.QBenchmarkMetric] = ...
        CacheReferences: ClassVar[QTest.QBenchmarkMetric] = ...
        CacheWriteMisses: ClassVar[QTest.QBenchmarkMetric] = ...
        CacheWrites: ClassVar[QTest.QBenchmarkMetric] = ...
        ContextSwitches: ClassVar[QTest.QBenchmarkMetric] = ...
        EmulationFaults: ClassVar[QTest.QBenchmarkMetric] = ...
        Events: ClassVar[QTest.QBenchmarkMetric] = ...
        FramesPerSecond: ClassVar[QTest.QBenchmarkMetric] = ...
        InstructionReads: ClassVar[QTest.QBenchmarkMetric] = ...
        Instructions: ClassVar[QTest.QBenchmarkMetric] = ...
        MajorPageFaults: ClassVar[QTest.QBenchmarkMetric] = ...
        MinorPageFaults: ClassVar[QTest.QBenchmarkMetric] = ...
        PageFaults: ClassVar[QTest.QBenchmarkMetric] = ...
        RefCPUCycles: ClassVar[QTest.QBenchmarkMetric] = ...
        StalledCycles: ClassVar[QTest.QBenchmarkMetric] = ...
        WalltimeMilliseconds: ClassVar[QTest.QBenchmarkMetric] = ...
        WalltimeNanoseconds: ClassVar[QTest.QBenchmarkMetric] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QTest.QBenchmarkMetric: ...
        def __and__(self, other: typing.SupportsInt) -> QTest.QBenchmarkMetric: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QTest.QBenchmarkMetric: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QTest.QBenchmarkMetric: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QTest.QBenchmarkMetric: ...
        def __rand__(self, other: typing.SupportsInt) -> QTest.QBenchmarkMetric: ...
        def __rmul__(self, other: typing.SupportsInt) -> QTest.QBenchmarkMetric: ...
        def __ror__(self, other: typing.SupportsInt) -> QTest.QBenchmarkMetric: ...
        def __rsub__(self, other: typing.SupportsInt) -> QTest.QBenchmarkMetric: ...
        def __rxor__(self, other: typing.SupportsInt) -> QTest.QBenchmarkMetric: ...
        def __sub__(self, other: typing.SupportsInt) -> QTest.QBenchmarkMetric: ...
        def __xor__(self, other: typing.SupportsInt) -> QTest.QBenchmarkMetric: ...

    class QTouchEventSequence(shiboken2.Object):
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def commit(self, processEvents: bool = ...) -> None: ...
        @overload
        def move(self, touchId: int, pt: PySide2.QtCore.QPoint, widget: typing.Union[PySide2.QtWidgets.QWidget,None] = ...) -> QTest.QTouchEventSequence: ...
        @overload
        def move(self, touchId: int, pt: PySide2.QtCore.QPoint, window: typing.Union[PySide2.QtGui.QWindow,None] = ...) -> QTest.QTouchEventSequence: ...
        @overload
        def press(self, touchId: int, pt: PySide2.QtCore.QPoint, widget: typing.Union[PySide2.QtWidgets.QWidget,None] = ...) -> QTest.QTouchEventSequence: ...
        @overload
        def press(self, touchId: int, pt: PySide2.QtCore.QPoint, window: typing.Union[PySide2.QtGui.QWindow,None] = ...) -> QTest.QTouchEventSequence: ...
        @overload
        def release(self, touchId: int, pt: PySide2.QtCore.QPoint, widget: typing.Union[PySide2.QtWidgets.QWidget,None] = ...) -> QTest.QTouchEventSequence: ...
        @overload
        def release(self, touchId: int, pt: PySide2.QtCore.QPoint, window: typing.Union[PySide2.QtGui.QWindow,None] = ...) -> QTest.QTouchEventSequence: ...
        def stationary(self, touchId: int) -> QTest.QTouchEventSequence: ...

    class TestFailMode:
        Abort: ClassVar[QTest.TestFailMode] = ...
        Continue: ClassVar[QTest.TestFailMode] = ...
        values: ClassVar[dict] = ...
        name: Any
        @classmethod
        def __init__(cls, *args, **kwargs) -> None: ...
        def __add__(self, other: typing.SupportsInt) -> QTest.TestFailMode: ...
        def __and__(self, other: typing.SupportsInt) -> QTest.TestFailMode: ...
        def __bool__(self) -> bool: ...
        def __eq__(self, other: object) -> bool: ...
        def __ge__(self, other: object) -> bool: ...
        def __gt__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> Any: ...
        def __int__(self) -> int: ...
        def __le__(self, other: object) -> bool: ...
        def __lt__(self, other: object) -> bool: ...
        def __mul__(self, other: typing.SupportsInt) -> QTest.TestFailMode: ...
        def __ne__(self, other: object) -> bool: ...
        def __or__(self, other: typing.SupportsInt) -> QTest.TestFailMode: ...
        def __pos__(self) -> Any: ...
        def __radd__(self, other: typing.SupportsInt) -> QTest.TestFailMode: ...
        def __rand__(self, other: typing.SupportsInt) -> QTest.TestFailMode: ...
        def __rmul__(self, other: typing.SupportsInt) -> QTest.TestFailMode: ...
        def __ror__(self, other: typing.SupportsInt) -> QTest.TestFailMode: ...
        def __rsub__(self, other: typing.SupportsInt) -> QTest.TestFailMode: ...
        def __rxor__(self, other: typing.SupportsInt) -> QTest.TestFailMode: ...
        def __sub__(self, other: typing.SupportsInt) -> QTest.TestFailMode: ...
        def __xor__(self, other: typing.SupportsInt) -> QTest.TestFailMode: ...
    Abort: ClassVar[QTest.TestFailMode] = ...
    AlignmentFaults: ClassVar[QTest.QBenchmarkMetric] = ...
    BitsPerSecond: ClassVar[QTest.QBenchmarkMetric] = ...
    BranchInstructions: ClassVar[QTest.QBenchmarkMetric] = ...
    BranchMisses: ClassVar[QTest.QBenchmarkMetric] = ...
    BusCycles: ClassVar[QTest.QBenchmarkMetric] = ...
    BytesAllocated: ClassVar[QTest.QBenchmarkMetric] = ...
    BytesPerSecond: ClassVar[QTest.QBenchmarkMetric] = ...
    CPUCycles: ClassVar[QTest.QBenchmarkMetric] = ...
    CPUMigrations: ClassVar[QTest.QBenchmarkMetric] = ...
    CPUTicks: ClassVar[QTest.QBenchmarkMetric] = ...
    CacheMisses: ClassVar[QTest.QBenchmarkMetric] = ...
    CachePrefetchMisses: ClassVar[QTest.QBenchmarkMetric] = ...
    CachePrefetches: ClassVar[QTest.QBenchmarkMetric] = ...
    CacheReadMisses: ClassVar[QTest.QBenchmarkMetric] = ...
    CacheReads: ClassVar[QTest.QBenchmarkMetric] = ...
    CacheReferences: ClassVar[QTest.QBenchmarkMetric] = ...
    CacheWriteMisses: ClassVar[QTest.QBenchmarkMetric] = ...
    CacheWrites: ClassVar[QTest.QBenchmarkMetric] = ...
    Click: ClassVar[QTest.KeyAction] = ...
    ContextSwitches: ClassVar[QTest.QBenchmarkMetric] = ...
    Continue: ClassVar[QTest.TestFailMode] = ...
    EmulationFaults: ClassVar[QTest.QBenchmarkMetric] = ...
    Events: ClassVar[QTest.QBenchmarkMetric] = ...
    FramesPerSecond: ClassVar[QTest.QBenchmarkMetric] = ...
    InstructionReads: ClassVar[QTest.QBenchmarkMetric] = ...
    Instructions: ClassVar[QTest.QBenchmarkMetric] = ...
    MajorPageFaults: ClassVar[QTest.QBenchmarkMetric] = ...
    MinorPageFaults: ClassVar[QTest.QBenchmarkMetric] = ...
    MouseClick: ClassVar[QTest.MouseAction] = ...
    MouseDClick: ClassVar[QTest.MouseAction] = ...
    MouseMove: ClassVar[QTest.MouseAction] = ...
    MousePress: ClassVar[QTest.MouseAction] = ...
    MouseRelease: ClassVar[QTest.MouseAction] = ...
    PageFaults: ClassVar[QTest.QBenchmarkMetric] = ...
    Press: ClassVar[QTest.KeyAction] = ...
    RefCPUCycles: ClassVar[QTest.QBenchmarkMetric] = ...
    Release: ClassVar[QTest.KeyAction] = ...
    Shortcut: ClassVar[QTest.KeyAction] = ...
    StalledCycles: ClassVar[QTest.QBenchmarkMetric] = ...
    WalltimeMilliseconds: ClassVar[QTest.QBenchmarkMetric] = ...
    WalltimeNanoseconds: ClassVar[QTest.QBenchmarkMetric] = ...
    mouseDoubleClickInterval: ClassVar[int] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def addColumnInternal(cls, id: int, name: bytes) -> None: ...
    @classmethod
    def asciiToKey(cls, ascii: int) -> PySide2.QtCore.Qt.Key: ...
    @classmethod
    def compare_ptr_helper(cls, t1: int, t2: int, actual: bytes, expected: bytes, file: bytes, line: int) -> bool: ...
    @classmethod
    def compare_string_helper(cls, t1: bytes, t2: bytes, actual: bytes, expected: bytes, file: bytes, line: int) -> bool: ...
    @classmethod
    def createTouchDevice(cls, devType: PySide2.QtGui.QTouchDevice.DeviceType = ...) -> PySide2.QtGui.QTouchDevice: ...
    @classmethod
    def currentAppName(cls) -> bytes: ...
    @classmethod
    def currentDataTag(cls) -> bytes: ...
    @classmethod
    def currentTestFailed(cls) -> bool: ...
    @classmethod
    def currentTestFunction(cls) -> bytes: ...
    @classmethod
    @overload
    def ignoreMessage(cls, type: PySide2.QtCore.QtMsgType, message: bytes) -> None: ...
    @classmethod
    @overload
    def ignoreMessage(cls, type: PySide2.QtCore.QtMsgType, messagePattern: PySide2.QtCore.QRegularExpression) -> None: ...
    @classmethod
    @overload
    def keyClick(cls, widget: PySide2.QtWidgets.QWidget, key: PySide2.QtCore.Qt.Key, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def keyClick(cls, widget: PySide2.QtWidgets.QWidget, key: int, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def keyClick(cls, window: PySide2.QtGui.QWindow, key: PySide2.QtCore.Qt.Key, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def keyClick(cls, window: PySide2.QtGui.QWindow, key: int, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., delay: int = ...) -> None: ...
    @classmethod
    def keyClicks(cls, widget: PySide2.QtWidgets.QWidget, sequence: str, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def keyEvent(cls, action: QTest.KeyAction, widget: PySide2.QtWidgets.QWidget, ascii: int, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def keyEvent(cls, action: QTest.KeyAction, widget: PySide2.QtWidgets.QWidget, key: PySide2.QtCore.Qt.Key, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def keyEvent(cls, action: QTest.KeyAction, window: PySide2.QtGui.QWindow, ascii: int, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def keyEvent(cls, action: QTest.KeyAction, window: PySide2.QtGui.QWindow, key: PySide2.QtCore.Qt.Key, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def keyPress(cls, widget: PySide2.QtWidgets.QWidget, key: PySide2.QtCore.Qt.Key, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def keyPress(cls, widget: PySide2.QtWidgets.QWidget, key: int, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def keyPress(cls, window: PySide2.QtGui.QWindow, key: PySide2.QtCore.Qt.Key, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def keyPress(cls, window: PySide2.QtGui.QWindow, key: int, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def keyRelease(cls, widget: PySide2.QtWidgets.QWidget, key: PySide2.QtCore.Qt.Key, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def keyRelease(cls, widget: PySide2.QtWidgets.QWidget, key: int, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def keyRelease(cls, window: PySide2.QtGui.QWindow, key: PySide2.QtCore.Qt.Key, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def keyRelease(cls, window: PySide2.QtGui.QWindow, key: int, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def keySequence(cls, widget: PySide2.QtWidgets.QWidget, keySequence: typing.Union[PySide2.QtGui.QKeySequence,str]) -> None: ...
    @classmethod
    @overload
    def keySequence(cls, window: PySide2.QtGui.QWindow, keySequence: typing.Union[PySide2.QtGui.QKeySequence,str]) -> None: ...
    @classmethod
    def keyToAscii(cls, key: PySide2.QtCore.Qt.Key) -> int: ...
    @classmethod
    @overload
    def mouseClick(cls, widget: PySide2.QtWidgets.QWidget, button: PySide2.QtCore.Qt.MouseButton, stateKey: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., pos: PySide2.QtCore.QPoint = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def mouseClick(cls, window: PySide2.QtGui.QWindow, button: PySide2.QtCore.Qt.MouseButton, stateKey: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., pos: PySide2.QtCore.QPoint = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def mouseDClick(cls, widget: PySide2.QtWidgets.QWidget, button: PySide2.QtCore.Qt.MouseButton, stateKey: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., pos: PySide2.QtCore.QPoint = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def mouseDClick(cls, window: PySide2.QtGui.QWindow, button: PySide2.QtCore.Qt.MouseButton, stateKey: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., pos: PySide2.QtCore.QPoint = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def mouseEvent(cls, action: QTest.MouseAction, widget: PySide2.QtWidgets.QWidget, button: PySide2.QtCore.Qt.MouseButton, stateKey: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier], pos: PySide2.QtCore.QPoint, delay: int = ...) -> None: ...
    @classmethod
    @overload
    def mouseEvent(cls, action: QTest.MouseAction, window: PySide2.QtGui.QWindow, button: PySide2.QtCore.Qt.MouseButton, stateKey: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier], pos: PySide2.QtCore.QPoint, delay: int = ...) -> None: ...
    @classmethod
    @overload
    def mouseMove(cls, widget: PySide2.QtWidgets.QWidget, pos: PySide2.QtCore.QPoint = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def mouseMove(cls, window: PySide2.QtGui.QWindow, pos: PySide2.QtCore.QPoint = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def mousePress(cls, widget: PySide2.QtWidgets.QWidget, button: PySide2.QtCore.Qt.MouseButton, stateKey: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., pos: PySide2.QtCore.QPoint = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def mousePress(cls, window: PySide2.QtGui.QWindow, button: PySide2.QtCore.Qt.MouseButton, stateKey: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., pos: PySide2.QtCore.QPoint = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def mouseRelease(cls, widget: PySide2.QtWidgets.QWidget, button: PySide2.QtCore.Qt.MouseButton, stateKey: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., pos: PySide2.QtCore.QPoint = ..., delay: int = ...) -> None: ...
    @classmethod
    @overload
    def mouseRelease(cls, window: PySide2.QtGui.QWindow, button: PySide2.QtCore.Qt.MouseButton, stateKey: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier] = ..., pos: PySide2.QtCore.QPoint = ..., delay: int = ...) -> None: ...
    @classmethod
    def qCleanup(cls) -> None: ...
    @classmethod
    def qElementData(cls, elementName: bytes, metaTypeId: int) -> int: ...
    @classmethod
    def qExpectFail(cls, dataIndex: bytes, comment: bytes, mode: QTest.TestFailMode, file: bytes, line: int) -> bool: ...
    @classmethod
    @overload
    def qFindTestData(cls, basepath: str, file: typing.Union[bytes,None] = ..., line: int = ..., builddir: typing.Union[bytes,None] = ...) -> str: ...
    @classmethod
    @overload
    def qFindTestData(cls, basepath: bytes, file: typing.Union[bytes,None] = ..., line: int = ..., builddir: typing.Union[bytes,None] = ...) -> str: ...
    @classmethod
    def qGlobalData(cls, tagName: bytes, typeId: int) -> int: ...
    @classmethod
    def qRun(cls) -> int: ...
    @classmethod
    def qSkip(cls, message: bytes, file: bytes, line: int) -> None: ...
    @classmethod
    def qWaitForWindowActive(cls, widget: PySide2.QtWidgets.QWidget, timeout: int = ...) -> bool: ...
    @classmethod
    def qWaitForWindowExposed(cls, widget: PySide2.QtWidgets.QWidget, timeout: int = ...) -> bool: ...
    @classmethod
    @overload
    def sendKeyEvent(cls, action: QTest.KeyAction, widget: PySide2.QtWidgets.QWidget, code: PySide2.QtCore.Qt.Key, ascii: int, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier], delay: int = ...) -> None: ...
    @classmethod
    @overload
    def sendKeyEvent(cls, action: QTest.KeyAction, widget: PySide2.QtWidgets.QWidget, code: PySide2.QtCore.Qt.Key, text: str, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier], delay: int = ...) -> None: ...
    @classmethod
    @overload
    def sendKeyEvent(cls, action: QTest.KeyAction, window: PySide2.QtGui.QWindow, code: PySide2.QtCore.Qt.Key, ascii: int, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier], delay: int = ...) -> None: ...
    @classmethod
    @overload
    def sendKeyEvent(cls, action: QTest.KeyAction, window: PySide2.QtGui.QWindow, code: PySide2.QtCore.Qt.Key, text: str, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier], delay: int = ...) -> None: ...
    @classmethod
    def setBenchmarkResult(cls, result: float, metric: QTest.QBenchmarkMetric) -> None: ...
    @classmethod
    def setMainSourcePath(cls, file: bytes, builddir: typing.Union[bytes,None] = ...) -> None: ...
    @classmethod
    @overload
    def simulateEvent(cls, widget: PySide2.QtWidgets.QWidget, press: bool, code: int, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier], text: str, repeat: bool, delay: int = ...) -> None: ...
    @classmethod
    @overload
    def simulateEvent(cls, window: PySide2.QtGui.QWindow, press: bool, code: int, modifier: typing.Union[PySide2.QtCore.Qt.KeyboardModifiers,PySide2.QtCore.Qt.KeyboardModifier], text: str, repeat: bool, delay: int = ...) -> None: ...
    @classmethod
    def testObject(cls) -> PySide2.QtCore.QObject: ...
    @classmethod
    def toPrettyCString(cls, unicode: bytes, length: int) -> bytes: ...
    @classmethod
    @overload
    def touchEvent(cls, widget: PySide2.QtWidgets.QWidget, device: PySide2.QtGui.QTouchDevice, autoCommit: bool = ...) -> QTest.QTouchEventSequence: ...
    @classmethod
    @overload
    def touchEvent(cls, window: PySide2.QtGui.QWindow, device: PySide2.QtGui.QTouchDevice, autoCommit: bool = ...) -> QTest.QTouchEventSequence: ...
